// Public blog content. Pure data module (no JSX) so the prerender script can
// import slugs too. Body is a list of typed blocks rendered as React elements.
//
// Block shapes:
//   ['p', 'paragraph text']
//   ['h2', 'heading']
//   ['h3', 'subheading']
//   ['ul', ['item one', 'item two']]
//   ['table', { head: ['A', 'B'], rows: [['a1', 'b1'], ['a2', 'b2']] }]

export const POSTS = [
  {
    slug: 'b2b-eposta-bulma-rehberi',
    title: 'B2B E-posta Bulma Rehberi: Bir Firmadaki Doğru Kişiye Nasıl Ulaşılır',
    metaTitle: 'B2B E-posta Bulma Rehberi: Doğru Kişiye Nasıl Ulaşılır',
    metaDescription: 'Bir firmada karar vericinin iş e-postasını bulmanın yöntemleri: pattern mantığı, doğrulama, catch-all domainler ve KVKK. Uygulamalı, güncel rehber.',
    author: 'ATAOL AI Techs',
    keyword: 'b2b e-posta bulma',
    excerpt: 'Bir firmada karar vericinin iş e-postasını bulmanın çalışan bir sistemi: pattern mantığı, doğrulama, catch-all domainler ve KVKK.',
    related: ['karar-vericisinin-epostasini-nasil-bulursun', 'sirket-eposta-adresi-bulma-yontemleri', 'dogrulanmis-is-epostasi-bulma', 'info-yerine-dogru-kisiye-ulasmak', 'b2b-lead-listesi-olusturma', 'turkiyede-b2b-musteri-bulma'],
    body: [
      ['p', 'Bir firmayı müşteri yapmak istiyorsun. Web sitesine giriyorsun, tek gördüğün adres bir info@ kutusu. O adrese yazdığın e-postaların çoğu bir yere varmıyor, çünkü orayı kimse ciddiye almıyor. Oysa ulaşman gereken kişi belli: o firmadaki satış direktörü, kurucu ya da operasyon müdürü. Sorun onu bulmak değil, ona giden iş e-postasını bulmak.'],
      ['p', 'Bu rehber, tam olarak bunu nasıl yapacağını anlatıyor. Tahmin ve şansı bırakıp, çalışan bir sistem kuracağız.'],
      ['h2', 'Neden info@ çözüm değil'],
      ['p', 'Genel adresler (info@, iletisim@, destek@) bir havuzdur. Oraya düşen mesajlar çoğu zaman bir asistan tarafından elenir, sınıflandırılır ya da hiç açılmaz. Sana lazım olan karar verici o kutuyu genelde hiç görmez.'],
      ['p', 'İş e-postası ise kişiseldir: ad ve soyadın domaine bağlanmış halidir. Doğru kişinin kişisel iş adresine giden bir mesajın açılma ve yanıt alma olasılığı, genel bir kutuya göre kat kat yüksektir. Bu yüzden hedefimiz her zaman kişiye özel adrestir.'],
      ['h2', 'Bir iş e-postasının anatomisi'],
      ['p', 'Her iş e-postası iki parçadan oluşur: yerel kısım (@ işaretinden önce) ve domain (@ işaretinden sonra). Domaini bulmak kolaydır, firmanın web sitesidir. İş burada yerel kısmı çözmektir.'],
      ['p', 'Firmalar yerel kısmı rastgele oluşturmaz. Neredeyse tüm kurumlar tek bir kalıp kullanır ve tüm çalışanlara aynı kalıbı uygular. En yaygın kalıplar şunlardır:'],
      ['ul', ['ad.soyad@firma.com', 'adsoyad@firma.com', 'a.soyad@firma.com (ilk harf, sonra soyad)', 'asoyad@firma.com', 'ad_soyad@firma.com', 'soyad.ad@firma.com', 'ad@firma.com']],
      ['p', 'Bir firmanın hangi kalıbı kullandığını bir kez çözersen, o firmadaki herkesin adresini üretebilirsin. Bir çalışanın adresini bir yerde gördüysen (LinkedIn, web sitesi, imza), kalıbı geri çıkarıp diğerlerine uygularsın.'],
      ['h3', 'Türkçe karakter tuzağı'],
      ['p', 'Türkiye firmalarında sık atlanan bir nokta var. Şükrü Güneş adlı biri için adres neredeyse hiçbir zaman şükrü.güneş@ olmaz. Türkçe karakterler İngilizce karşılıklarına çevrilir: ş yerine s, ğ yerine g, ı yerine i, ç yerine c, ö yerine o, ü yerine u. Yani doğru tahmin sukru.gunes@firma.com olur. Bu çeviriyi yapmadan üretilen her kalıp baştan yanlıştır.'],
      ['h2', 'E-posta bulmanın dört yöntemi'],
      ['p', 'Elinde dört temel yol var. Her birinin ayrı bir gücü ve sınırı var.'],
      ['h3', '1. Web sitesi ve iletişim sayfası taraması'],
      ['p', 'Firmanın kendi sitesi çoğu zaman en dürüst kaynaktır. İletişim, hakkımızda, ekip ve kurumsal sayfalarında gerçek adresler açıkça yazabilir. Bu adresler tahmin değil, doğrulanmış gerçeklerdir. İlk adımın her zaman burası olsun.'],
      ['h3', '2. Kalıp üretme ve doğrulama'],
      ['p', 'Site adres vermiyorsa, kişinin adını ve firmanın domainini biliyorsan kalıpları üretir, sonra hangisinin gerçek olduğunu doğrularsın. Bu ikilinin birleşimi aslında bir e-posta bulucudur: üret, doğrula, gerçeği döndür. Doğrulama olmadan bu yöntem sadece tahmindir.'],
      ['h3', '3. Veritabanı tabanlı araçlar'],
      ['p', 'Hunter, Apollo gibi araçların arkasında geniş kişi veritabanları vardır. Bir domain verirsin, sana o firmadaki kişileri ve adreslerini döndürür. Kapsamları geniştir ama maliyetlidir ve her firmayı, özellikle küçük yerel firmaları bilmezler.'],
      ['h3', '4. LinkedIn üzerinden çapraz doğrulama'],
      ['p', 'LinkedIn, doğru kişiyi ve unvanını bulmak için en iyi yerdir. Adresi doğrudan vermez ama adı ve firmayı verir. Adı alıp kalıba çevirir, doğrularsın. Ayrıca bir kişinin gerçek adresini bir yerde görürsen, firmanın kalıbını çözmek için çapraz kontrol sağlar.'],
      ['h2', 'Doğrulama olmadan tahmin işe yaramaz'],
      ['p', 'Burası çoğu rehberin atladığı yer. Bir kalıp ürettin diyelim: ad.soyad@firma.com. Bu adres gerçekten var mı, yoksa boşa mı yazıyorsun? Doğrulama bunu söyler.'],
      ['p', 'Doğrulama üç katmanda çalışır:'],
      ['ul', ['MX kaydı: Domainin e-posta alabilen bir sunucusu var mı. Yoksa hiçbir adres çalışmaz.', 'Kutu kontrolü: Sunucuya bağlanıp o yerel kısmın gerçekten var olup olmadığı sorulur.', 'Catch-all durumu: Bazı firmalar her adrese evet der ayarındadır. Bu durumda hangi kalıbın gerçek olduğunu ayırt edemezsin.']],
      ['p', 'Doğrulamayı atlamanın bedeli bounce tur. Var olmayan adreslere gönderim yaptıkça gönderen itibarın düşer ve zamanla gerçek adreslere bile ulaşamamaya başlarsın.'],
      ['h2', 'KVKK ve soğuk iletişimde e-posta'],
      ['p', 'Türkiye de e-posta ile soğuk iletişim yaparken iki çerçeveyi bilmek gerekir. Kişisel verilerin işlenmesi KVKK kapsamındadır. Ticari elektronik ileti gönderimi ise 6563 sayılı kanun ve İleti Yönetim Sistemi (İYS) ile düzenlenir. Bu bir hukuki tavsiye değildir; ölçeklenmeden önce bir hukukçuya danışmanı öneririz. Doğru yaklaşım, az sayıda ve gerçekten ilgili firmaya kişiselleştirilmiş ulaşmaktır.'],
      ['h2', 'Hangi yöntem sana uygun'],
      ['p', 'Solo kurucuysan ve az sayıda ama doğru firmayı hedefliyorsan, site taraması ve kalıp artı doğrulama kombinasyonu genelde yeter. Hacmin arttıkça veritabanı tabanlı bir aracı doğrulamayla birlikte kullanmak işini hızlandırır. Değişmeyen sıralama şudur: önce doğru kişiyi belirle, sonra adresi üret, sonra mutlaka doğrula, en son gönder.'],
    ],
    faq: [
      { q: 'Bir firmanın kullandığı e-posta kalıbını nasıl anlarım?', a: 'O firmadan bir kişinin gerçek adresini bir yerde bulup adını kalıba geri çevirirsin. Örneğin a.gunes@firma.com adresi, firmanın ilk harf nokta soyad kalıbını kullandığını gösterir.' },
      { q: 'Tahmin ettiğim adresin gerçek olduğunu nasıl bilirim?', a: 'Doğrulama ile. MX kaydı, kutu kontrolü ve catch-all durumu bakılır. Catch-all olmayan bir domainde doğrulama kesin sonuç verir.' },
      { q: 'Sadece info@ adresi bulabiliyorum, ne yapmalıyım?', a: 'Önce LinkedIn den doğru kişiyi bul, adını firma domainiyle birleştirip kalıp üret ve doğrula. Başka yol yoksa info@ üzerinden yazarken konuya doğru kişinin adını ekle.' },
    ],
  },

  {
    slug: 'karar-vericisinin-epostasini-nasil-bulursun',
    title: 'Bir Firmanın Karar Vericisinin E-postasını Nasıl Bulursun',
    metaTitle: 'Karar Vericinin E-postasını Bulma: Adım Adım',
    metaDescription: 'Bir firmada doğru karar vericiyi belirleyip iş e-postasına ulaşmanın adım adım yolu: unvan haritası, kalıp üretme, doğrulama ve alternatif kişi.',
    author: 'ATAOL AI Techs',
    keyword: 'karar verici e-postası bulma',
    excerpt: 'Doğru karar vericiyi belirleyip e-postasına ulaşmanın tek firma üzerinden adım adım anlatımı.',
    related: ['b2b-eposta-bulma-rehberi', 'info-yerine-dogru-kisiye-ulasmak', 'dogrulanmis-is-epostasi-bulma'],
    body: [
      ['p', 'Karar vericinin e-postasını bulmak iki işi karıştırmamakla başlar: önce doğru kişiyi belirlemek, sonra o kişinin adresini bulmak. Çoğu kişi ikinciyle uğraşıp birinciyi atlar ve yanlış insana yazar. Bu yazıda tek bir firma üzerinden, sırayla ilerleyeceğiz.'],
      ['h2', 'Adım 1: Doğru unvanı belirle'],
      ['p', 'Sunduğun şeye göre kararı verecek kişi değişir. Yazacağın kişi, teklifinden en çok etkilenen ve bütçesine hükmeden kişidir. Kaba bir harita:'],
      ['ul', ['Satış veya pazarlama çözümü satıyorsan: Satış Direktörü, Pazarlama Müdürü, CMO', 'Operasyon veya verimlilik çözümü: Operasyon Müdürü, COO', 'Yazılım veya teknik ürün: CTO, Teknoloji Müdürü, Ürün Müdürü', 'İnsan kaynakları çözümü: İK Müdürü, People Lead', 'Küçük firma veya erken startup: doğrudan kurucu ya da genel müdür']],
      ['p', 'Kural şudur: 10 kişilik bir firmada kurucuya yaz, 500 kişilik bir firmada ilgili departman müdürüne. Büyük firmada kurucuya yazmak neredeyse hiç yanıt getirmez.'],
      ['h2', 'Adım 2: O kişinin adını bul'],
      ['p', 'Unvanı belirledin, şimdi o unvandaki gerçek kişiyi bulacaksın. En hızlı kaynak LinkedIn: firma sayfasına gir, çalışanlar sekmesinden unvana göre filtrele. İkinci kaynak firmanın ekip veya yönetim sayfasıdır. Üçüncüsü basın haberleri ve etkinlik konuşmacı listeleridir; yöneticiler oralarda adıyla geçer.'],
      ['h2', 'Adım 3: Adı firma kalıbına çevir'],
      ['p', 'Adı ve firmanın domainini biliyorsun. Şimdi olası adresleri üret. Firmalar tek bir kalıp kullanır, o yüzden en yaygın kalıpları sırayla dener, doğrularsın. Kalıpların tam listesi ve Türkçe karakter çevirisi için B2B e-posta bulma rehberimize bakabilirsin. Kısaca: en olası aday ad.soyad@domain ve a.soyad@domain kalıplarıdır.'],
      ['h2', 'Adım 4: Adayları doğrula'],
      ['p', 'Ürettiğin adayların hangisi gerçek? Doğrulama söyler. Adayları en olasıdan başlayarak doğrula, ilk geçerli olanda dur. Domain catch-all ise doğrulama karar veremez; o zaman en olası kalıbı tahmin olarak alırsın. Doğrulamanın nasıl çalıştığını doğrulanmış e-posta yazımızda ayrıntılı anlattık.'],
      ['h2', 'Adım 5: Bulamazsan kademeli in'],
      ['p', 'Karar vericinin adresini bir türlü doğrulayamıyorsan boşuna ısrar etme. Bir kademe alta in: o kişinin ekibinden birine ulaş, seni doğru kişiye yönlendirsin. Ya da bulduğun geçerli bir adres varsa, mesajında asıl konuşmak istediğin kişinin adını ve unvanını belirt; iç yönlendirme çoğu zaman işe yarar.'],
      ['h2', 'Örnek: tek firma üzerinden'],
      ['p', 'Diyelim ki bir e-ticaret KOBİ sine lojistik yazılımı satıyorsun. Karar verici muhtemelen Operasyon Müdürü. LinkedIn de firmanın operasyon müdürünün Deniz Yılmaz olduğunu buldun. Firmanın sitesinde bir çalışanın imzasında a.kaya@firma.com gördün, demek ki kalıp ilk harf nokta soyad. O halde en güçlü aday d.yilmaz@firma.com. Doğruladın, geçerli çıktı. Artık doğru kişiye, doğru adrese yazabilirsin.'],
    ],
    faq: [
      { q: 'Büyük bir firmada kime yazmalıyım?', a: 'Kurucuya değil, teklifinle ilgili departmanın müdürüne. Büyük firmada kurucuya yazılan soğuk e-postalar neredeyse hiç yanıt almaz.' },
      { q: 'Doğru kişiyi buldum ama e-postasını doğrulayamıyorum, ne yaparım?', a: 'Bir kademe alta inip ekibinden birine ulaş ya da geçerli başka bir adrese yazıp mesajında asıl kişinin adını ve unvanını belirterek iç yönlendirme iste.' },
      { q: 'LinkedIn dışında doğru kişiyi nereden bulabilirim?', a: 'Firmanın ekip ve yönetim sayfaları, basın haberleri ve sektör etkinliklerinin konuşmacı listeleri iyi kaynaklardır.' },
    ],
  },

  {
    slug: 'sirket-eposta-adresi-bulma-yontemleri',
    title: 'Şirket E-posta Adresi Bulma Yöntemleri',
    metaTitle: 'Şirket E-posta Adresi Bulma Yöntemleri',
    metaDescription: 'Bir şirketin e-posta adresini bulmanın ücretsiz ve ücretli yöntemleri, doğruluk ve maliyet karşılaştırması, Google arama operatörleri ve catch-all gerçeği.',
    author: 'ATAOL AI Techs',
    keyword: 'şirket e-posta adresi bulma',
    excerpt: 'Ücretsiz ve ücretli yöntemleri doğruluk, hız ve maliyet açısından dürüstçe karşılaştıran uygulamalı bir rehber.',
    related: ['b2b-eposta-bulma-rehberi', 'dogrulanmis-is-epostasi-bulma', 'karar-vericisinin-epostasini-nasil-bulursun'],
    body: [
      ['p', 'Bir şirketin e-posta adresini bulmanın birden çok yolu var ve hepsi aynı sonucu vermez. Bazıları bedava ama yavaş, bazıları hızlı ama maliyetli. Bu yazıda yöntemleri açıkça karşılaştırıp hangi durumda hangisini seçeceğini netleştiriyoruz.'],
      ['h2', 'Ücretsiz yöntemler'],
      ['p', 'Para harcamadan gidebileceğin üç yol var. İlki, firmanın web sitesini taramak: iletişim, hakkımızda ve ekip sayfalarında gerçek adresler açıkça yazabilir. İkincisi, Google arama operatörleriyle adresleri açığa çıkarmak. Üçüncüsü, kişinin adını firmanın kalıbına çevirip aday adresler üretmek.'],
      ['h3', 'Google arama operatörü örnekleri'],
      ['p', 'Arama motoru, sitenin gömdüğü adresleri bulmak için güçlü bir araçtır. Şu kalıpları dene:'],
      ['ul', ['site:firma.com e-posta ya da site:firma.com iletisim', '"@firma.com" ile firma adı birlikte aratmak', 'Kişinin adı ile "@firma.com" birlikte aratmak', 'intext operatörüyle belirli bir unvanı ve firmayı aramak']],
      ['h2', 'Ücretli araçlar ne katar'],
      ['p', 'Hunter, Apollo gibi araçların arkasında geniş veritabanları vardır. Domaini verirsin, firmadaki kişileri ve adresleri döndürür. Sana kazandırdığı şey hız ve kapsamdır. Sınırı ise şudur: küçük ve yerel firmaları çoğu zaman bilmezler, ve maliyet kullanımla birlikte artar.'],
      ['h2', 'Yöntem karşılaştırması'],
      ['table', {
        head: ['Yöntem', 'Doğruluk', 'Hız', 'Maliyet'],
        rows: [
          ['Site tarama', 'Yüksek (gerçek adres)', 'Yavaş', 'Bedava'],
          ['Google operatörleri', 'Orta', 'Orta', 'Bedava'],
          ['Kalıp + doğrulama', 'Yüksek (doğrulanırsa)', 'Hızlı', 'Düşük'],
          ['Veritabanı aracı', 'Değişken', 'Çok hızlı', 'Yüksek'],
        ],
      }],
      ['h2', 'Catch-all gerçeği'],
      ['p', 'Hangi yöntemi seçersen seç, bir adresin gerçekten çalıştığından emin olmak için doğrulama gerekir. Ama bazı domainler catch-all ayarındadır: var olmayan adreslere bile kabul derler. Böyle bir domainde doğrulama hangi kalıbın gerçek olduğunu söyleyemez, en olası kalıbı tahmin olarak alırsın. Bu, ücretli aracın bile kesin sonuç veremeyeceği bir durumdur.'],
      ['h2', 'Yasal sınır'],
      ['p', 'Herkese açık kaynaklardan iş iletişim bilgisi bulmak yaygın bir pratiktir. Kritik olan bu veriyi nasıl kullandığındır. KVKK ve ticari elektronik ileti kurallarına uygun, kişiselleştirilmiş ve alakalı iletişim kur; toplu ve izinsiz gönderimden kaçın.'],
    ],
    faq: [
      { q: 'Bir şirketin e-postasını tamamen ücretsiz bulabilir miyim?', a: 'Çoğu zaman evet. Site tarama, Google operatörleri ve kalıp üretme bedavadır. Eksik olan tek şey doğrulamadır; onun için genelde ucuz bir araç gerekir.' },
      { q: 'Google ile adres bulmak için hangi operatörü kullanmalıyım?', a: 'site:firma.com iletisim ve firma adıyla birlikte "@firma.com" aramaları en çok işe yarayanlardır.' },
      { q: 'Ücretli araç her firmayı bulur mu?', a: 'Hayır. Veritabanları büyük ve bilinen firmalarda güçlüdür; küçük ve yerel firmalarda çoğu zaman eksik kalır.' },
    ],
  },

  {
    slug: 'info-yerine-dogru-kisiye-ulasmak',
    title: 'info@ Yerine Doğru Kişiye Ulaşmak: Genel Adreslerin Tuzağı',
    metaTitle: 'info@ Yerine Doğru Kişiye Ulaşmak',
    metaDescription: 'Genel e-posta adresleri neden yanıt getirmez ve karar vericiye nasıl ulaşırsın. info@ elindeyse ne yapman gerektiği ve örnek ilk temas mesajı.',
    author: 'ATAOL AI Techs',
    keyword: 'info e-posta yerine doğru kişi',
    excerpt: 'Genel adreslerin neden çalışmadığı ve karar vericiye ulaşmanın pratik yolları, örnek ilk temas mesajıyla.',
    related: ['b2b-eposta-bulma-rehberi', 'karar-vericisinin-epostasini-nasil-bulursun'],
    body: [
      ['p', 'Bir firmaya ulaşmak istiyorsun ama elindeki tek adres info@ ya da iletisim@. O adrese yazdığın mesajların çoğunun neden yanıtsız kaldığını ve gerçekten doğru kişiye nasıl ulaşacağını anlatalım.'],
      ['h2', 'Genel adresler neden yanıtlanmaz'],
      ['p', 'Genel kutular bir ortak havuzdur. Genelde bir asistan, resepsiyon ya da otomatik bir sistem tarafından karşılanır. Gelen mesajlar müşteri talebi, fatura, başvuru gibi kategorilere ayrılır. Senin soğuk teklifin bu akışta en düşük önceliklidir ve karar vericiye çoğu zaman hiç ulaşmaz. Yani sorun mesajının değil, kutunun kendisidir.'],
      ['h2', 'Karar vericiye ulaşmanın üç yolu'],
      ['p', 'info@ ile uğraşmak yerine doğru kişinin kişisel iş adresini hedefle. Üç yol var. Birincisi, LinkedIn den doğru unvandaki kişiyi bul, adını firma kalıbına çevir ve doğrula. İkincisi, firmanın ekip sayfasından adları topla. Üçüncüsü, elindeki geçerli bir adres varsa oradan iç yönlendirme iste. Bu yolların ayrıntısı için karar vericinin e-postasını bulma yazımıza bakabilirsin.'],
      ['h2', 'info@ elindeyse ne yapmalı'],
      ['p', 'Bazen küçük bir firmada gerçekten tek kutu info@ dır ve karar verici de onu okur. Bu durumda info@ kötü bir seçenek değildir, yeter ki mesajını doğru kurgula. İki şeye dikkat et: konuya ulaşmak istediğin kişinin adını ve unvanını ekle ki mesaj doğru kişiye yönlendirilsin, ve ilk cümlede neden yazdığını net söyle ki eleyen kişi değerini anlasın.'],
      ['h2', 'Örnek ilk temas'],
      ['p', 'Konu: Deniz Yılmaz için, operasyon verimliliği. Merhaba, mesajımı operasyondan sorumlu Deniz Yılmaz a iletebilir misiniz. Firmanızın sipariş yoğunluğu arttıkça hazırlık sürelerini kısaltan bir çözüm üzerinde çalışıyoruz. Kısa bir örnek gönderebilirim, ilgilenirse birkaç dakikalık bir görüşme ayarlayabiliriz. Teşekkürler.'],
      ['p', 'Bu mesaj kısa, doğru kişiyi adıyla işaret ediyor ve eleyen kişiye ne yapması gerektiğini söylüyor. info@ üzerinden bile yanıt alma şansın böyle artar.'],
    ],
    faq: [
      { q: 'info@ adresine yazmak tamamen zaman kaybı mı?', a: 'Hayır. Küçük firmalarda karar verici o kutuyu okuyabilir. Mesajında doğru kişinin adını belirtir ve değeri net anlatırsan yanıt şansın artar.' },
      { q: 'Karar vericinin kişisel adresini bulamıyorum, ne yaparım?', a: 'LinkedIn den adını bulup firma kalıbına çevir ve doğrula. Olmazsa geçerli başka bir adrese yazıp iç yönlendirme iste.' },
    ],
  },

  {
    slug: 'dogrulanmis-is-epostasi-bulma',
    title: 'Doğrulanmış İş E-postası Bulma: Ücretsiz ve Ücretli Yöntemler',
    metaTitle: 'Doğrulanmış İş E-postası Bulma',
    metaDescription: 'E-posta doğrulama neden şart, nasıl çalışır ve bounce oranını nasıl düşürürsün. Ücretsiz sınırlar, kullanım başına doğrulama ve Türkiye den gönderimde dikkat.',
    author: 'ATAOL AI Techs',
    keyword: 'e-posta doğrulama',
    excerpt: 'Doğrulamanın teknik gerçeği, ücretsiz ve ücretli seçenekler ve bounce oranını düşürmenin somut yolları.',
    related: ['b2b-eposta-bulma-rehberi', 'sirket-eposta-adresi-bulma-yontemleri'],
    body: [
      ['p', 'Bir e-posta adresi bulmak yarısıdır. Diğer yarısı o adresin gerçekten çalıştığından emin olmaktır. Doğrulama bunu yapar ve atlanırsa hem isabetin hem de gönderme yeteneğin zarar görür.'],
      ['h2', 'Doğrulama neden şart'],
      ['p', 'Var olmayan bir adrese gönderim yaptığında mesaj geri döner, buna bounce denir. Bounce oranın yükseldikçe e-posta sağlayıcıları seni şüpheli görür ve gönderen itibarın düşer. Sonuçta gerçek ve geçerli adreslere gönderdiğin mesajlar bile spam klasörüne düşmeye başlar. Yani doğrulama sadece bu adres doğru mu sorusu değil, uzun vadede gönderebiliyor muyum sorusudur.'],
      ['h2', 'Doğrulama nasıl çalışır'],
      ['p', 'Doğrulama katmanlı bir kontroldür. Önce MX kaydına bakılır: domainin e-posta alabilen bir sunucusu var mı. Yoksa hiçbir adres çalışmaz. Sonra sunucuya bağlanılıp o yerel kısmın var olup olmadığı sorulur. Cevaba göre adres geçerli, geçersiz ya da belirsiz olarak işaretlenir.'],
      ['h3', 'Catch-all neden belirsizlik yaratır'],
      ['p', 'Bazı domainler catch-all ayarındadır: var olmayan adreslere bile kabul derler. Böyle bir sunucu her adaya evet dediği için hangi kalıbın gerçek olduğunu ayırt edemezsin. Bu domainlerde doğrulama sana kesin bir evet veremez; en olası kalıbı tahmin olarak, düşük güvenle alırsın. Bunu bilmek, sonuçları yanlış yorumlamanı engeller.'],
      ['h2', 'Ücretsiz sınırlar ve kullanım başına doğrulama'],
      ['p', 'Kendi altyapında SMTP seviyesinde doğrulama yapmak çoğu ortamda mümkün değildir, çünkü giden bağlantılar engellidir. Bu yüzden pratikte bir doğrulama servisi kullanılır. Bu servislerin çoğu az sayıda ücretsiz deneme kredisi verir, sonrası kullanım başınadır. Kullanım başına model startuplar için sağlıklıdır: maliyet ancak gerçekten doğrulama yaptığında oluşur, sabit bir abonelik yükü olmaz.'],
      ['h2', 'Bounce oranını düşürme taktikleri'],
      ['ul', ['Göndermeden önce her adresi doğrula, tahminle gönderme.', 'Catch-all domainlerdeki tahmin adreslere toplu gönderim yapma, tek tek ve dikkatli git.', 'Listeyi temiz tut; eski ve tepki almayan adresleri ayıkla.', 'Yeni bir gönderen alan adında hacmi yavaş yavaş artır.']],
      ['h2', 'Türkiye den gönderimde dikkat'],
      ['p', 'Gönderdiğin domainin kimlik kayıtları (SPF ve DKIM) düzgün ayarlı olmalı ki mesajların spam e düşmesin. Ayrıca ticari elektronik ileti kurallarına uy: gerçekten ilgili ve az sayıda alıcıya kişiselleştirilmiş yaz. Doğrulama isabeti artırır ama kuralları o değil, senin yaklaşımın belirler.'],
    ],
    faq: [
      { q: 'Doğrulama olmadan gönderirsem ne olur?', a: 'Var olmayan adreslere gönderim bounce üretir, gönderen itibarın düşer ve zamanla geçerli adreslere bile ulaşamamaya başlarsın.' },
      { q: 'Catch-all domainde adresi kesin doğrulayabilir miyim?', a: 'Hayır. Catch-all sunucu her adrese kabul dediği için doğrulama karar veremez; en olası kalıbı tahmin olarak, düşük güvenle alırsın.' },
      { q: 'Kendi başıma doğrulama yapabilir miyim?', a: 'Çoğu ortamda giden SMTP bağlantıları engelli olduğu için pratikte bir doğrulama servisi kullanılır. Kullanım başına ödeme modeli startuplar için en uygunudur.' },
    ],
  },

  {
    slug: 'b2b-lead-listesi-olusturma',
    title: 'B2B Lead Listesi Sıfırdan Nasıl Oluşturulur',
    metaTitle: 'B2B Lead Listesi Nasıl Oluşturulur',
    metaDescription: 'İdeal müşteri profilinden CSV çıktısına kadar B2B lead listesi oluşturmanın uçtan uca sistemi: kaynaklar, doğru kişi ve e-posta, kolon şablonu ve outreach.',
    author: 'ATAOL AI Techs',
    keyword: 'b2b lead listesi oluşturma',
    excerpt: 'İdeal müşteri profilinden outreach a hazır CSV ye kadar uçtan uca, uygulanabilir bir lead listesi sistemi.',
    related: ['b2b-eposta-bulma-rehberi', 'karar-vericisinin-epostasini-nasil-bulursun', 'dogrulanmis-is-epostasi-bulma'],
    body: [
      ['p', 'İyi bir lead listesi rastgele toplanmış isimler değildir. Doğru firmalar, doğru kişiler ve doğrulanmış adreslerden oluşan, kullanıma hazır bir yapıdır. Bu yazıda ideal müşteri profilinden outreach a hazır bir CSV ye kadar sistemi kuruyoruz.'],
      ['h2', 'Adım 1: İdeal müşteri profilini tanımla'],
      ['p', 'Herkesi hedeflemek hiç kimseyi hedeflememektir. Önce ideal müşterini birkaç somut ölçütle tanımla: sektör, firma büyüklüğü (çalışan sayısı), lokasyon ve seni gerçekten ihtiyaç duyar hale getiren tetikleyici durum. Örneğin sipariş hacmi büyüyen 20 ila 100 çalışanlı e-ticaret firmaları. Bu netlik, listenin geri kalanını kolaylaştırır.'],
      ['h2', 'Adım 2: Hedef firma listesi çıkar'],
      ['p', 'Profiline uyan firmaları toplamak için birden çok kaynağı birleştir. Sektör dizinleri ve ticaret odası listeleri, Google Haritalar aramaları, LinkedIn firma aramaları ve sektörel etkinlik katılımcı listeleri iyi başlangıçlardır. Amaç 20 ila 50 gerçekten uygun firmadır, binlerce alakasız isim değil.'],
      ['h2', 'Adım 3: Her firmada doğru kişi ve e-posta'],
      ['p', 'Firma listesi tek başına yetmez, her firmada karar vericiyi ve adresini bulman gerekir. Unvanı belirle, kişiyi LinkedIn den bul, adını firma kalıbına çevir ve doğrula. Bu sürecin ayrıntısı için karar vericinin e-postasını bulma yazımıza bakabilirsin.'],
      ['h2', 'Adım 4: Listeyi doğru kolonlarla yapılandır'],
      ['p', 'Listeyi bir araca aktaracaksan kolonların standart olması gerekir. Çoğu outreach aracının beklediği asgari yapı şudur:'],
      ['table', {
        head: ['Kolon', 'Açıklama'],
        rows: [
          ['email', 'Doğrulanmış iş e-postası'],
          ['first_name', 'Kişinin adı (kişiselleştirme için)'],
          ['company', 'Firma adı'],
          ['title', 'Unvan'],
          ['website', 'Firma domaini'],
        ],
      }],
      ['p', 'Bu kolonları CSV olarak dışa aktardığında, liste Instantly ya da Lemlist gibi araçlara doğrudan yüklenebilir hale gelir.'],
      ['h2', 'Adım 5: Listeyi outreach a dönüştür'],
      ['p', 'Liste hazır olduğunda son adım kişiselleştirilmiş ulaşımdır. Her satır için firmaya özel, kısa ve tek çağrılı bir mesaj yaz. Toplu ve aynı metni gönderme; first_name ve company kolonlarını kullanarak her mesajı ilgili kişiye özel hale getir. Az sayıda ama isabetli gönderim, çok sayıda alakasız gönderimden her zaman daha iyidir.'],
      ['h2', 'Türkiye ve ihracat için kaynak farkı'],
      ['p', 'Yurt içi listelerde ticaret odası kayıtları, sektör dernekleri ve Google Haritalar güçlü kaynaklardır. İhracat hedefliyorsan hedef ülkenin sektör dizinleri, fuar katılımcı listeleri ve LinkedIn ülke filtreleri devreye girer. Her iki durumda da mantık aynıdır: profil, firma, kişi, adres, doğrulama.'],
    ],
    faq: [
      { q: 'Lead listesi ne kadar büyük olmalı?', a: 'Büyüklük değil isabet önemlidir. 20 ila 50 gerçekten uygun firma, binlerce alakasız isimden çok daha iyi sonuç verir.' },
      { q: 'CSV de hangi kolonlar olmalı?', a: 'Asgari olarak email, first_name, company, title ve website. Bu yapı çoğu outreach aracına doğrudan yüklenir.' },
      { q: 'İhracat için lead listesini nereden çıkarırım?', a: 'Hedef ülkenin sektör dizinleri, fuar katılımcı listeleri ve LinkedIn ülke filtreleri en verimli kaynaklardır.' },
    ],
  },

  {
    slug: 'turkiyede-b2b-musteri-bulma',
    title: 'Türkiye de B2B Müşteri Bulmanın Yolları',
    metaTitle: 'Türkiye de B2B Müşteri Bulmanın Yolları',
    metaDescription: 'Türkiye de B2B müşteri bulmanın pratik yolları: ideal müşteri profili, yerel firma kaynakları, doğru kişiye ulaşma, kanallar ve ilk 10 müşteri planı.',
    author: 'ATAOL AI Techs',
    keyword: 'türkiye b2b müşteri bulma',
    excerpt: 'Türkiye pazarında B2B müşteri bulmanın uçtan uca yolu: yerel kaynaklar, doğru kişi, kanallar ve ilk 10 müşteri için pratik plan.',
    related: ['kvkk-iys-soguk-eposta', 'ihracatta-musteri-bulma', 'kobi-dijital-musteri-edinme', 'teknokent-startup-ilk-musteri', 'b2b-eposta-bulma-rehberi'],
    body: [
      ['p', 'Türkiye de B2B satış hem ilişki hem de sistem işidir. İlişki güven getirir ama ilişkiyi kuracak ilk teması bir yerden başlatman gerekir. Bu yazı, sıfırdan başlayıp ilk müşterilerine ulaşman için izleyebileceğin somut yolu anlatıyor.'],
      ['h2', 'Önce ideal müşteriyi netleştir'],
      ['p', 'Herkese satmaya çalışmak en yavaş yoldur. Kime sattığını birkaç somut ölçütle tanımla: sektör, firma büyüklüğü, şehir ve seni gerçekten ihtiyaç haline getiren durum. Örneğin İstanbul ve çevresinde, sipariş hacmi büyüyen 20 ila 100 çalışanlı üretim firmaları. Bu netlik hem firma bulmayı hem de mesajı kolaylaştırır.'],
      ['h2', 'Yerel firma kaynakları'],
      ['p', 'Türkiye de hedef firma listesi çıkarmak için güçlü yerel kaynaklar var. Bunları birleştir:'],
      ['ul', ['Ticaret ve sanayi odaları üye listeleri', 'Organize sanayi bölgeleri (OSB) firma dizinleri', 'Sektör dernekleri ve ihracatçı birlikleri', 'Google Haritalar aramaları (şehir ve sektör bazlı)', 'LinkedIn firma aramaları (ülke ve sektör filtresi)']],
      ['p', 'Amaç binlerce isim değil, profiline uyan 20 ila 50 gerçek firmadır.'],
      ['h2', 'Doğru kişiye ulaş'],
      ['p', 'Firma listesi tek başına yetmez; her firmada karar vericiyi ve iş e-postasını bulman gerekir. Unvanı belirle, kişiyi bul, adını firma kalıbına çevir ve doğrula. Bu sürecin tamamı için B2B e-posta bulma rehberimize bakabilirsin.'],
      ['h2', 'Hangi kanaldan ulaşmalı'],
      ['p', 'Türkiye de en çok işe yarayan üç kanal soğuk e-posta, LinkedIn ve referanstır. Soğuk e-posta ölçeklenebilir ve doğrudandır. LinkedIn ısınma için iyidir. Referans ise en yüksek dönüşümü verir ama başta elinde olmaz, ilk müşterilerle onu inşa edersin. Fuar ve sektör etkinlikleri de yüz yüze temas için değerlidir.'],
      ['h2', 'Yasal çerçeveyi atlama'],
      ['p', 'Soğuk e-posta gönderirken KVKK ve ticari elektronik ileti kurallarını bilmen gerekir. Kısaca: az sayıda, gerçekten ilgili firmaya, kişiselleştirilmiş ve red imkanı sunan bir yaklaşım güvenlidir. Ayrıntı için KVKK ve İYS ye uygun soğuk e-posta yazımıza göz at.'],
      ['h2', 'İlk 10 müşteri için pratik plan'],
      ['p', 'Bir haftalık basit bir plan: profiline uyan 30 firma çıkar, her birinde doğru kişiyi ve doğrulanmış e-postayı bul, her firmaya özel kısa bir mesaj yaz, gönder ve yanıt vermeyene birkaç gün sonra tek bir takip at. 30 hedeften birkaç görüşme, birkaç görüşmeden ilk müşterilerin çıkar. Sistem büyümenin değil, başlamanın yoludur.'],
    ],
    faq: [
      { q: 'Türkiye de B2B müşteri bulmaya nereden başlamalıyım?', a: 'İdeal müşteri profilini netleştirerek. Sektör, büyüklük, şehir ve tetikleyici durumu tanımla; sonra bu profile uyan firmaları odalar, OSB dizinleri ve LinkedIn üzerinden çıkar.' },
      { q: 'En hızlı sonuç veren kanal hangisi?', a: 'Ölçeklenebilirlik açısından kişiselleştirilmiş soğuk e-posta. En yüksek dönüşüm referanstan gelir ama referansı ilk müşterilerle inşa edersin.' },
      { q: 'Soğuk e-posta Türkiye de yasal mı?', a: 'Kurallara uyulduğunda evet. Az sayıda, ilgili firmaya, kişiselleştirilmiş ve kolay red imkanı sunan gönderim güvenlidir. Ayrıntı için KVKK yazımıza bakın.' },
    ],
  },

  {
    slug: 'kvkk-iys-soguk-eposta',
    title: 'KVKK ve İYS ye Uygun Soğuk E-posta Nasıl Gönderilir',
    metaTitle: 'KVKK ve İYS ye Uygun Soğuk E-posta',
    metaDescription: 'Türkiye de soğuk e-posta yasal mı? KVKK, 6563 sayılı kanun ve İYS çerçevesinde ticari elektronik ileti kuralları, B2B istisnası ve uyumlu gönderim.',
    author: 'ATAOL AI Techs',
    keyword: 'kvkk soğuk e-posta',
    excerpt: 'Soğuk e-postanın KVKK ve İYS çerçevesindeki yeri, B2B istisnası ve uyumlu gönderim için pratik kurallar.',
    related: ['turkiyede-b2b-musteri-bulma', 'b2b-eposta-bulma-rehberi'],
    body: [
      ['p', 'Soğuk e-posta Türkiye de yasal mı sorusunun cevabı nasıl gönderdiğine bağlıdır. İki ayrı çerçeveyi bilmek gerekir ve çoğu kişi bunları karıştırır. Bu yazı ikisini net ayırıyor. Not: bu bir hukuki tavsiye değildir, ölçeklenmeden önce bir hukukçuya danışmanı öneririz.'],
      ['h2', 'İki ayrı çerçeve'],
      ['p', 'Birincisi kişisel verilerin korunmasıdır. Bir kişinin adı ve e-postası kişisel veridir ve işlenmesi 6698 sayılı KVKK kapsamındadır. İkincisi ticari iletişimdir. Ticari amaçlı elektronik ileti göndermek 6563 sayılı kanun ve İleti Yönetim Sistemi (İYS) ile düzenlenir. Uyum için ikisine de bakman gerekir.'],
      ['h2', 'Ticari elektronik ileti ve onay'],
      ['p', 'Genel kural, ticari elektronik ileti göndermeden önce alıcının onayının alınmasıdır. Yani rastgele kişilere izinsiz toplu ticari e-posta göndermek genel kurala aykırıdır.'],
      ['h3', 'B2B istisnası'],
      ['p', 'Önemli bir istisna vardır: tacir ve esnaflara, ticari faaliyetleriyle ilgili iletilerde önceden onay aranmaz. Yani bir firmaya iş amaçlı ulaşman, bireysel bir tüketiciye reklam göndermenden farklıdır. Ancak bu istisna sınırsız değildir: her iletide kolay bir red imkanı sunmak ve alıcı reddederse gönderimi durdurmak zorundasın. Gönderenlerin İYS üzerinden onay ve red kayıtlarını yönetmesi beklenir.'],
      ['h2', 'Kişisel veri tarafı'],
      ['p', 'İş e-postasını herkese açık bir kaynaktan bulman, onu istediğin gibi kullanabileceğin anlamına gelmez. Veriyi hangi amaçla işlediğini bilmeli, gerektiğinde aydınlatma yükümlülüğünü yerine getirmeli ve veriyi gereğinden uzun saklamamalısın. İlgili kişi verisinin silinmesini isteyebilir.'],
      ['h2', 'Uyumlu nasıl gönderilir'],
      ['ul', ['Bireysel tüketicilere değil, iş amaçlı olarak firmalara ve yetkililere yaz.', 'Toplu ve alakasız değil, az sayıda ve gerçekten ilgili firmaya kişiselleştirilmiş gönder.', 'Her mesajda kolay bir red imkanı bırak ve reddedeni bir daha rahatsız etme.', 'Verinin kaynağını, amacını ve saklama süresini kayıt altına al.']],
      ['p', 'Özetle, spam mantığıyla toplu gönderim risklidir; hedefli, kişisel ve red hakkı tanıyan B2B iletişim ise makul bir zemindedir.'],
    ],
    faq: [
      { q: 'Firmalara izinsiz soğuk e-posta gönderebilir miyim?', a: 'Tacir ve esnaflara ticari faaliyetleriyle ilgili iletilerde önceden onay aranmaz, ancak her iletide kolay bir red imkanı sunmalı ve reddedene göndermeyi durdurmalısınız.' },
      { q: 'İYS ye kayıt gerekli mi?', a: 'Ticari elektronik ileti gönderenlerin İYS üzerinden onay ve red yönetimi yapması beklenir. Detay ve güncel yükümlülükler için bir hukukçuya danışın.' },
      { q: 'Herkese açık bir e-postayı bulmam yeterli mi?', a: 'Bulmak kullanımı serbest hale getirmez. Veriyi meşru bir amaçla, aydınlatma ve saklama kurallarına uygun işlemeniz gerekir.' },
    ],
  },

  {
    slug: 'ihracatta-musteri-bulma',
    title: 'İhracatta Yurt Dışı Müşteri Bulma: Soğuk E-posta Rehberi',
    metaTitle: 'İhracatta Yurt Dışı Müşteri Bulma',
    metaDescription: 'İhracatta yurt dışı müşteri bulmanın dijital yolu: hedef pazar seçimi, yurt dışı firma kaynakları, doğru kişiye ulaşma ve yerel dilde soğuk e-posta.',
    author: 'ATAOL AI Techs',
    keyword: 'ihracatta müşteri bulma',
    excerpt: 'Yurt dışı müşteri bulmanın dijital yolu: hedef pazar, firma kaynakları, doğru kişi ve yerel dilde soğuk e-posta.',
    related: ['turkiyede-b2b-musteri-bulma', 'b2b-lead-listesi-olusturma'],
    body: [
      ['p', 'İhracatta ilk müşteri artık çoğu zaman bir fuar salonunda değil, doğru kişiye giden iyi bir e-posta ile başlar. Yurt dışı müşteriyi dijital olarak bulmanın sistemini kuralım.'],
      ['h2', 'Hedef pazarı ve profili seç'],
      ['p', 'Her ülkeye aynı anda açılmak dağılmaktır. Önce ürünün için en uygun bir veya iki pazarı seç. Talep, rekabet, lojistik maliyeti ve dil kolaylığına bak. Sonra o pazarda ideal müşteri profilini tanımla: hangi sektör, hangi büyüklükte firma, hangi rol.'],
      ['h2', 'Yurt dışı firma kaynakları'],
      ['p', 'Hedef pazarda firma listesi çıkarmak için şu kaynakları birleştir:'],
      ['ul', ['Hedef ülkenin sektör dizinleri ve ticaret odası kayıtları', 'Uluslararası fuarların katılımcı ve ziyaretçi listeleri', 'LinkedIn ülke ve sektör filtreleri', 'B2B pazaryerleri ve sektörel platformlar', 'İhracatçı birlikleri ve ticaret ataşeliği yönlendirmeleri']],
      ['h2', 'Doğru kişiye ulaş'],
      ['p', 'Yurt dışı firmada da mantık aynıdır: doğru unvanı belirle, kişiyi bul, adını firma kalıbına çevir ve doğrula. Listeyi düzenli bir yapıya dökmek için B2B lead listesi oluşturma yazımızdaki kolon şablonunu kullanabilirsin.'],
      ['h2', 'Yerel dilde soğuk e-posta'],
      ['p', 'Almanya ya İngilizce, Fransa ya Fransızca yazmak fark yaratır. Alıcının dilinde, kısa ve tek çağrılı bir mesaj güven verir. Mesajı o firmaya özel bir detayla aç; genel geçer bir tanıtım değil, onların işine değen bir cümle ile başla. Zaman dilimini gözet, yanıt vermeyene birkaç gün sonra tek bir takip at.'],
      ['h2', 'Kültür ve takip'],
      ['p', 'Pazarlar farklı ritimlerde yanıt verir. Bazı ülkelerde doğrudan ve kısa mesaj tercih edilirken bazılarında daha resmi bir dil beklenir. İlk birkaç kampanyada neyin yanıt aldığını gözlemle ve mesajını ona göre ayarla. Sabır ve düzenli takip, ihracatta ilk müşteriyi getiren şeydir.'],
    ],
    faq: [
      { q: 'İhracatta hangi pazardan başlamalıyım?', a: 'Aynı anda çok pazara değil, talebi ve lojistiği uygun bir veya iki pazara odaklan. Dil kolaylığı da ilk pazar seçiminde önemlidir.' },
      { q: 'Yurt dışı firmaların e-postasını nasıl bulurum?', a: 'Ülke sektör dizinleri, fuar katılımcı listeleri ve LinkedIn ülke filtreleriyle firmayı ve kişiyi bul, adını firma kalıbına çevirip doğrula.' },
      { q: 'Soğuk e-postayı hangi dilde yazmalıyım?', a: 'Mümkünse alıcının yerel dilinde. Kısa, kişiselleştirilmiş ve tek çağrılı bir mesaj yanıt oranını artırır.' },
    ],
  },

  {
    slug: 'kobi-dijital-musteri-edinme',
    title: 'KOBİ ler için Dijital Müşteri Edinme Rehberi',
    metaTitle: 'KOBİ ler için Dijital Müşteri Edinme Rehberi',
    metaDescription: 'Sınırlı bütçeli KOBİ ler için dijital müşteri edinme: outbound ile hızlı başlangıç, adım adım süreç, düşük maliyetli araçlar ve neyi ölçmeli.',
    author: 'ATAOL AI Techs',
    keyword: 'kobi müşteri bulma',
    excerpt: 'Sınırlı bütçeli KOBİ ler için outbound temelli, hızlı ve ölçülebilir bir dijital müşteri edinme yaklaşımı.',
    related: ['turkiyede-b2b-musteri-bulma', 'b2b-eposta-bulma-rehberi'],
    body: [
      ['p', 'Bir KOBİ nin büyük bir pazarlama bütçesi ya da satış ekibi olmayabilir. İyi haber şu: dijital müşteri edinmek için ikisine de mecbur değilsin. Sınırlı kaynakla hızlı sonuç veren bir yaklaşım kuralım.'],
      ['h2', 'Outbound neden KOBİ için hızlı'],
      ['p', 'İçerik ve reklamla gelen inbound talebin oluşması aylar alır ve bütçe ister. Outbound ise tersini yapar: sen doğru firmaya gidersin. Bir KOBİ için outbound in avantajı, ilk müşteriyi haftalar içinde getirebilmesi ve maliyetinin çoğunlukla senin zamanın olmasıdır.'],
      ['h2', 'Adım adım süreç'],
      ['p', 'Karmaşık bir sisteme gerek yok. Beş adım yeterlidir:'],
      ['ul', ['Hedefle: ideal müşteri profilini tanımla ve profiline uyan firmaları çıkar.', 'Bul: her firmada karar vericiyi ve doğrulanmış iş e-postasını bul.', 'Yaz: her firmaya özel, kısa ve tek çağrılı bir mesaj hazırla.', 'Gönder: mesajı kendi gelen kutundan gönder.', 'Takip et: yanıt vermeyene birkaç gün sonra tek bir hatırlatma at.']],
      ['h2', 'Düşük maliyetli araç yaklaşımı'],
      ['p', 'Pahalı bir yığın araca ihtiyacın yok. Firma ve kişi bulmayı büyük ölçüde ücretsiz kaynaklarla yapabilir, yalnızca e-posta doğrulama gibi kritik adımlarda kullanım başına ödeyen ucuz bir çözüm kullanabilirsin. Böylece sabit gider yerine, ancak gerçekten iş yaptığında oluşan bir maliyetin olur.'],
      ['h2', 'Neyi ölçmeli'],
      ['p', 'Ölçemediğin şeyi geliştiremezsin ama fazla metrikle de boğulma. Bir KOBİ için üç sayı yeter: kaç firmaya ulaştın, kaçından yanıt aldın, kaçı görüşmeye ya da müşteriye döndü. Bu üç sayı mesajının ve hedeflemenin işe yarayıp yaramadığını söyler.'],
    ],
    faq: [
      { q: 'KOBİ için inbound mı outbound mu daha iyi?', a: 'Hızlı başlangıç için outbound. İçerik ve reklamla gelen inbound zaman ve bütçe ister; outbound ilk müşteriyi haftalar içinde getirebilir.' },
      { q: 'Müşteri edinmek için pahalı araçlar şart mı?', a: 'Hayır. Firma ve kişi bulmayı büyük ölçüde ücretsiz yapabilir, yalnızca doğrulama gibi adımlarda kullanım başına ödeyen ucuz bir çözüm kullanabilirsiniz.' },
      { q: 'Neyi ölçmeliyim?', a: 'Üç sayı yeter: kaç firmaya ulaştınız, kaçından yanıt aldınız, kaçı görüşmeye veya müşteriye döndü.' },
    ],
  },

  {
    slug: 'teknokent-startup-ilk-musteri',
    title: 'Teknokent ve Erken Startup için İlk Müşteri Stratejisi',
    metaTitle: 'Erken Startup için İlk Müşteri Stratejisi',
    metaDescription: 'Ürün hazır ama müşteri yok sorununa çözüm: erken startup için ilk müşteriyi bulma, ekosistemi kullanma, elle outreach ve pilot teklif stratejisi.',
    author: 'ATAOL AI Techs',
    keyword: 'startup ilk müşteri',
    excerpt: 'Ürün var müşteri yok sorununa erken startup için pratik ilk müşteri stratejisi: ekosistem, elle outreach ve pilot teklif.',
    related: ['turkiyede-b2b-musteri-bulma', 'karar-vericisinin-epostasini-nasil-bulursun'],
    body: [
      ['p', 'Ürün hazır ama müşteri yok. Erken bir startup için en yaygın ve en can sıkıcı durum budur. İlk müşteriyi bulmak, sonraki yüz müşteriyi bulmaktan farklı bir iştir ve farklı bir yaklaşım ister.'],
      ['h2', 'İlk müşteri neden farklıdır'],
      ['p', 'İlk müşteri sadece gelir değildir. Ürününün gerçekten işe yaradığının kanıtı, geri bildirim kaynağı ve bir sonraki müşteriye göstereceğin referanstır. Bu yüzden ilk müşteriyi ölçeklenebilir bir kanaldan değil, elle ve tek tek kazanırsın. Bu aşamada verimlilik değil, öğrenme ve kanıt önemlidir.'],
      ['h2', 'Ekosistemi kullan'],
      ['p', 'Bir teknokentte ya da hızlandırıcı programındaysan, çevrende hazır bir ağ var. Diğer kurucular, mentorlar ve program bağlantıları ilk görüşmeler için en sıcak kapıdır. İTÜ Çekirdek gibi ekosistemlerdeki kurucu toplulukları, hem ilk kullanıcılar hem de yönlendirmeler için güçlü bir başlangıçtır.'],
      ['h2', 'Doğrudan ve elle outreach'],
      ['p', 'Ekosistem yetmediğinde doğrudan hedefe gidersin. Ürününün en net fayda sağlayacağı 20 ila 30 firmayı seç, her birinde doğru kişiyi bul ve ona özel bir mesaj yaz. Bu aşamada otomasyon değil, dikkat kazandırır. Doğru kişiyi bulmanın yolu için karar vericinin e-postasını bulma yazımıza bakabilirsin.'],
      ['h2', 'İlk temasta ne söylemeli'],
      ['p', 'İlk mesajda ürününü satmaya çalışma, bir konuşma başlat. Onların yaşadığı somut bir sorunu adıyla koy ve kısa bir görüşme ya da küçük bir deneme öner. Erken aşamada insanlar bir ürüne değil, sorunlarını gerçekten anlayan bir kurucuya yanıt verir.'],
      ['h2', 'Pilot ve erken kullanıcı teklifi'],
      ['p', 'İlk müşterileri kazanmak için bir pilot ya da erken kullanıcı teklifi güçlü bir araçtır. Karşılığında ücret yerine ya da düşük ücretle, yakın geri bildirim ve bir referans istersin. Bu, hem müşterinin riskini düşürür hem de sana ürünü olgunlaştıracak en değerli veriyi verir. Birkaç memnun erken kullanıcı, bir sonraki aşamanın temelidir.'],
    ],
    faq: [
      { q: 'İlk müşteriyi nereden bulmalıyım?', a: 'Önce ekosisteminden: diğer kurucular, mentorlar ve program bağlantıları. Sonra doğrudan, ürününün en net fayda sağlayacağı 20 ila 30 firmaya elle ulaşarak.' },
      { q: 'İlk temasta ürünü mü anlatmalıyım?', a: 'Hayır. Bir konuşma başlat: alıcının somut bir sorununu adıyla koy ve kısa bir görüşme ya da küçük bir deneme öner.' },
      { q: 'Pilot teklifi vermeli miyim?', a: 'Erken aşamada evet. Düşük ücret ya da ücretsiz karşılığında yakın geri bildirim ve referans istemek, hem müşterinin riskini düşürür hem de ürünü olgunlaştırır.' },
    ],
  },

  {
    slug: 'eposta-bulucu-outreach-araclari-secimi',
    title: 'E-posta Bulucu ve Outreach Araçları: Nasıl Seçilir ve Alternatifler',
    metaTitle: 'E-posta Bulucu ve Outreach Araçları Nasıl Seçilir',
    metaDescription: 'E-posta bulucu, doğrulayıcı ve gönderim araçlarının farkı, hangisinin kime uygun olduğu ve bütçe, hacim ve Türkiye pazarına göre nasıl seçileceği.',
    author: 'ATAOL AI Techs',
    keyword: 'e-posta bulucu araçlar',
    excerpt: 'Bulucular, doğrulayıcılar ve gönderim platformlarının farkı ve bütçe, hacim ve Türkiye pazarına göre doğru aracı seçme rehberi.',
    related: ['apollo-alternatifi', 'hunter-alternatifi', 'startuplar-icin-uygun-crm', 'kendi-gelen-kutundan-gonderim', 'b2b-eposta-bulma-rehberi'],
    body: [
      ['p', 'Bu alanda onlarca araç var ve hepsi aynı işi yapmıyor. Yanlış kategoriden bir araca para ödemek sık yapılan bir hatadır. Önce kategorileri ayıralım, sonra kime hangisinin uyduğunu netleştirelim.'],
      ['h2', 'Araç kategorileri'],
      ['p', 'Piyasadaki araçlar aslında dört ayrı işi yapar:'],
      ['ul', ['Bulucular: bir domainde kişileri ve e-postaları bulur (örnek: Hunter, Apollo).', 'Doğrulayıcılar: bir adresin gerçekten çalışıp çalışmadığını kontrol eder.', 'Gönderim platformları: toplu dizi gönderimi, warmup ve otomasyon yapar (örnek: Instantly, Lemlist).', 'Hepsi bir arada: bulma, yazma ve pipeline yönetimini tek yerde toplar.']],
      ['p', 'Bir aracı almadan önce sorman gereken soru şu: benim asıl ihtiyacım bulmak mı, doğrulamak mı, göndermek mi, yoksa hepsini tek akışta yapmak mı?'],
      ['h2', 'Neye göre seçmeli'],
      ['p', 'Dört şeye bak: bütçe, hacim, Türkiye pazarındaki kapsam ve gönderim ihtiyacın. Az sayıda ama doğru firmaya ulaşan bir kurucu ile günde yüzlerce mesaj gönderen bir ekibin ihtiyacı tamamen farklıdır. Türkiye ve yerel KOBİ hedefliyorsan, büyük küresel veritabanlarının bu firmaları çoğu zaman eksik bildiğini de hesaba kat.'],
      ['h2', 'Kategori karşılaştırması'],
      ['table', {
        head: ['Kategori', 'Ne yapar', 'Kime uygun'],
        rows: [
          ['Bulucu', 'Kişi ve e-posta bulur', 'Liste çıkaran herkes'],
          ['Doğrulayıcı', 'Adresi doğrular', 'Bounce ı düşürmek isteyen'],
          ['Gönderim platformu', 'Toplu dizi ve warmup', 'Yüksek hacimli ekipler'],
          ['Hepsi bir arada', 'Bul, yaz, yönet', 'Solo kurucu ve KOBİ'],
        ],
      }],
      ['h2', 'Ücretsiz ve ücretli mantığı'],
      ['p', 'Bulma işinin büyük kısmı ücretsiz kaynaklarla yapılabilir. Asıl para harcanması gereken yer doğrulamadır. Bu yüzden sağlıklı bir kurgu, bulmayı ücretsiz katmana bırakıp yalnızca doğrulamayı kullanım başına ödemektir. Sabit ve yüksek bir abonelik, düşük hacimde çoğu zaman israftır.'],
      ['h2', 'AskDesk bu tabloda nerede durur'],
      ['p', 'AskDesk hepsi bir arada kategorisindedir: doğru kişiyi ve doğrulanmış e-postayı bulur, o firmaya özel e-postayı yazar ve pipeline ı yönetir. Ayırt edici yanı, bir toplu gönderim platformu olmamasıdır; e-postayı sen kendi gelen kutundan gönderirsin. Yüksek hacimli otomatik dizi gönderimi istiyorsan bir gönderim platformu daha uygundur. Doğru kişiyi bulup kişiselleştirilmiş ve kontrollü ulaşmak istiyorsan bu yaklaşım işini görür.'],
    ],
    faq: [
      { q: 'Bulucu ile gönderim platformu aynı şey mi?', a: 'Hayır. Bulucu kişi ve e-posta bulur; gönderim platformu toplu dizi ve warmup yapar. İhtiyacına göre farklı kategorilerdir.' },
      { q: 'Düşük hacimde pahalı abonelik gerekli mi?', a: 'Genelde hayır. Bulmayı ücretsiz yapıp yalnızca doğrulamayı kullanım başına ödemek düşük hacimde daha mantıklıdır.' },
      { q: 'Türkiye pazarı için nelere dikkat etmeliyim?', a: 'Büyük küresel veritabanları küçük ve yerel Türk firmalarını çoğu zaman eksik bilir. Yerel kaynakları ve doğrulamayı birlikte kullanmak daha isabetlidir.' },
    ],
  },

  {
    slug: 'apollo-alternatifi',
    title: 'Apollo.io Alternatifi: Küçük Ekipler İçin Uygun Seçenekler',
    metaTitle: 'Apollo.io Alternatifi Arayanlar İçin Seçenekler',
    metaDescription: 'Apollo.io ne işe yarar, güçlü ve zayıf yönleri ve küçük ekipler için uygun alternatifler. Maliyet, Türkiye kapsamı ve doğrulama açısından karşılaştırma.',
    author: 'ATAOL AI Techs',
    keyword: 'apollo alternatifi',
    excerpt: 'Apollo.io nun güçlü ve zayıf yönleri ve küçük ekipler için maliyet ve Türkiye kapsamı açısından uygun alternatifler.',
    related: ['eposta-bulucu-outreach-araclari-secimi', 'hunter-alternatifi', 'b2b-eposta-bulma-rehberi'],
    body: [
      ['p', 'Apollo.io güçlü bir araçtır ama herkes için doğru araç değildir. Bu yazıda Apollo nun ne işe yaradığını, nerede parladığını, nerede zorlandığını ve küçük bir ekip ya da kurucu için hangi alternatiflerin daha uygun olduğunu dürüstçe ele alıyoruz.'],
      ['h2', 'Apollo ne yapar'],
      ['p', 'Apollo, arkasında geniş bir kişi ve firma veritabanı olan bir satış zekası platformudur. Sektör, unvan, firma büyüklüğü gibi filtrelerle kişi listeleri çıkarır, e-postaları verir ve outreach özellikleri sunar. Güçlü yanı bu veritabanının kapsamıdır.'],
      ['h2', 'Nerede zorlanır'],
      ['ul', ['Maliyet: gerçek değeri veren özellikler üst planlarda açılır ve kullanıcı başına ücret küçük ekipte hızla artar.', 'Türkiye kapsamı: küçük ve yerel Türk firmalarında veritabanı çoğu zaman eksik kalır.', 'İhtiyaç uyumsuzluğu: az sayıda ama doğru firmayı hedefleyen biri için dev bir veritabanının çoğu kullanılmaz.']],
      ['h2', 'Alternatif yaklaşımlar'],
      ['p', 'Apollo yerine üç yol var. Birincisi, sadece bulma odaklı daha sade bir araç (örneğin Hunter). İkincisi, bulmayı ücretsiz kaynaklarla yapıp yalnızca doğrulamayı kullanım başına ödemek; bu, düşük hacimde en ekonomik yoldur. Üçüncüsü, bulma, yazma ve pipeline ı tek yerde toplayan hepsi bir arada bir çözüm.'],
      ['p', 'AskDesk bu üçüncü grupta yer alır ve Türkiye ile KOBİ odağı, kalıp artı doğrulama ile e-posta bulma ve kendi gelen kutundan gönderim yaklaşımıyla ayrışır. Yüksek hacimli veri madenciliği istiyorsan Apollo hâlâ güçlüdür; doğru kişiyi bulup kişiselleştirilmiş ulaşmak istiyorsan daha hafif bir çözüm yeter.'],
      ['h2', 'Kime hangisi uygun'],
      ['p', 'Büyük bir satış ekibin ve geniş bir veri iştahın varsa Apollo mantıklıdır. Solo kurucuysan, KOBİ isen ya da Türkiye odaklıysan, maliyeti kullanımla büyüyen ve yerel firmalarda daha isabetli bir alternatif genelde daha doğru bir tercihtir.'],
    ],
    faq: [
      { q: 'Apollo neden küçük ekipler için pahalı gelir?', a: 'Değerli özellikler üst planlarda açılır ve kullanıcı başına ücret küçük ekipte hızla birikir. Düşük hacimde bu maliyetin çoğu boşa gider.' },
      { q: 'Apollo Türkiye firmalarını iyi biliyor mu?', a: 'Büyük ve bilinen firmalarda güçlüdür ama küçük ve yerel Türk firmalarında veritabanı çoğu zaman eksik kalır.' },
      { q: 'Apollo yerine daha ucuz ne kullanabilirim?', a: 'Bulmayı ücretsiz yapıp yalnızca doğrulamayı kullanım başına ödeyen bir kurgu ya da bulma ve yazmayı tek yerde toplayan hepsi bir arada bir çözüm.' },
    ],
  },

  {
    slug: 'hunter-alternatifi',
    title: 'Hunter.io Alternatifi: E-posta Bulmanın Daha Ekonomik Yolları',
    metaTitle: 'Hunter.io Alternatifi Arayanlar İçin Seçenekler',
    metaDescription: 'Hunter.io ne işe yarar ve arama başına kredi modeli ne zaman pahalı olur. E-posta bulmanın daha ekonomik alternatifleri ve doğrulama yaklaşımı.',
    author: 'ATAOL AI Techs',
    keyword: 'hunter alternatifi',
    excerpt: 'Hunter.io nun arama başına kredi modelinin sınırı ve e-posta bulmanın daha ekonomik alternatifleri.',
    related: ['eposta-bulucu-outreach-araclari-secimi', 'apollo-alternatifi', 'dogrulanmis-is-epostasi-bulma'],
    body: [
      ['p', 'Hunter.io, e-posta bulmak için en bilinen araçlardan biridir. Sade ve domain odaklıdır. Ama her aramanın bir krediye mal olduğu modeli, hacim arttıkça beklenmedik bir maliyete dönüşebilir. Alternatiflere bakalım.'],
      ['h2', 'Hunter ne yapar'],
      ['p', 'Hunter üç temel iş yapar: bir domaindeki e-postaları listeler (domain search), bir kişinin adresini tahmin eder (email finder) ve bir adresi doğrular (email verifier). Basitliği en güçlü yanıdır.'],
      ['h2', 'Kredi modelinin sınırı'],
      ['p', 'Hunter da her arama ve doğrulama bir krediyi tüketir. Az sayıda arama yapıyorsan ücretsiz katman yeter. Ama düzenli olarak liste çıkarıyorsan krediler hızla biter ve üst plana geçmek gerekir. Yani maliyet, kullanımınla birlikte ama sıçramalı bir şekilde artar.'],
      ['h2', 'Daha ekonomik alternatif: kalıp artı doğrulama'],
      ['p', 'E-posta bulmanın özü aslında kalıp üretmek ve doğrulamaktır. Kişinin adını ve firmanın domainini biliyorsan, olası adresleri ücretsiz üretebilir ve yalnızca doğrulama adımında ödeme yapabilirsin. Bu, arama başına ücret ödemekten çoğu zaman daha ucuzdur. Doğrulamanın nasıl çalıştığını doğrulanmış e-posta yazımızda ayrıntılı anlattık.'],
      ['h2', 'Diğer alternatifler'],
      ['p', 'Daha geniş bir veritabanı istiyorsan Apollo bir seçenektir ama maliyeti daha yüksektir. Bulma, yazma ve pipeline ı tek akışta istiyorsan hepsi bir arada bir çözüm daha verimlidir. AskDesk bu son grupta yer alır: kalıp artı doğrulama ile bulur, e-postayı yazar ve kendi gelen kutundan göndermene izin verir.'],
      ['h2', 'Kime hangisi uygun'],
      ['p', 'Ara sıra birkaç adres arıyorsan Hunter ın ücretsiz katmanı zaten yeter. Düzenli ve daha büyük hacimde çalışıyorsan, kalıp artı doğrulama temelli daha ekonomik bir yaklaşım ya da hepsi bir arada bir araç genelde daha mantıklıdır.'],
    ],
    faq: [
      { q: 'Hunter ne zaman pahalı olur?', a: 'Her arama ve doğrulama kredi tükettiği için düzenli liste çıkardığında krediler hızla biter ve üst plana geçmek gerekir.' },
      { q: 'Hunter dan daha ucuz e-posta nasıl bulurum?', a: 'Kişinin adını firma kalıbına çevirip olası adresleri ücretsiz üret, sadece doğrulama adımında kullanım başına öde.' },
      { q: 'Hunter ın ücretsiz katmanı yeterli mi?', a: 'Ara sıra birkaç arama için evet. Düzenli ve büyük hacimde çalışıyorsan yetersiz kalır.' },
    ],
  },

  {
    slug: 'startuplar-icin-uygun-crm',
    title: 'Startup lar için Uygun Fiyatlı CRM: Sade ve İşe Yarar Seçenekler',
    metaTitle: 'Startup lar için Uygun Fiyatlı CRM Seçenekleri',
    metaDescription: 'Büyük CRM ler erken startup a neden ağır gelir ve gerçekte neye ihtiyacın var. Sade pipeline, lead takibi ve uygun fiyatlı CRM seçenekleri.',
    author: 'ATAOL AI Techs',
    keyword: 'startup crm',
    excerpt: 'Büyük CRM lerin erken startup a neden ağır geldiği ve sade, uygun fiyatlı seçeneklerin gerçekte neye çözüm olduğu.',
    related: ['eposta-bulucu-outreach-araclari-secimi', 'turkiyede-b2b-musteri-bulma'],
    body: [
      ['p', 'Erken bir startup için CRM seçimi çoğu zaman yanlış yerden başlar: en güçlü ve en bilinen aracı seçmek. Oysa erken aşamada güç değil, sadelik kazandırır. Gerçekten neye ihtiyacın olduğuna bakalım.'],
      ['h2', 'Büyük CRM ler neden ağır gelir'],
      ['p', 'Salesforce ve HubSpot gibi platformlar güçlüdür ama büyük ekipler ve karmaşık süreçler için tasarlanmıştır. Erken bir startup için bunlar çoğu zaman fazla özellik, uzun kurulum ve gereksiz maliyet demektir. Kullanmadığın onlarca alan, seni yavaşlatır.'],
      ['h2', 'Gerçekte neye ihtiyacın var'],
      ['p', 'Erken aşamada bir CRM den beklediğin üç şey vardır: müşteri adaylarını bir yerde tutmak, her birinin hangi aşamada olduğunu görmek ve takip etmeyi unutmamak. Basit bir pipeline ve lead listesi bu ihtiyacın neredeyse tamamını karşılar.'],
      ['h2', 'Sade seçenekler kategorisi'],
      ['p', 'Bu ihtiyaca iki tür araç uyar. Birincisi, tek işi basit bir kanban pipeline sunmak olan hafif araçlardır. İkincisi, müşteri bulma, e-posta yazma ve pipeline ı tek yerde toplayan hepsi bir arada çözümlerdir. İkincisi, hem bulmayı hem yönetmeyi aynı yerde yaptığı için erken aşamada araç kalabalığını azaltır.'],
      ['h2', 'AskDesk in yaklaşımı'],
      ['p', 'AskDesk pipeline ı ayrı bir dev CRM olarak değil, müşteri bulma ve outreach akışının bir parçası olarak sunar. Doğru firmayı bulur, e-postayı yazar ve o firmayı pipeline a kart olarak eklersin; aşamalar arasında sürükleyerek takip edersin. Erken bir startup için bu, ayrı bir CRM kurup entegre etmekten daha az sürtünmelidir.'],
    ],
    faq: [
      { q: 'Erken startup a Salesforce ya da HubSpot şart mı?', a: 'Hayır. Bu platformlar büyük ekipler için tasarlanmıştır; erken aşamada fazla özellik, uzun kurulum ve gereksiz maliyet getirir.' },
      { q: 'Startup gerçekte CRM den ne bekler?', a: 'Adayları bir yerde tutmak, aşamalarını görmek ve takibi kaçırmamak. Basit bir pipeline bunu karşılar.' },
      { q: 'Ayrı bir CRM kurmak yerine ne yapabilirim?', a: 'Bulma, yazma ve pipeline ı tek yerde toplayan hepsi bir arada bir çözüm, erken aşamada araç kalabalığını azaltır.' },
    ],
  },

  {
    slug: 'kendi-gelen-kutundan-gonderim',
    title: 'Kendi Gelen Kutundan Gönderim: Instantly ve Lemlist e Farklı Bir Yaklaşım',
    metaTitle: 'Kendi Gelen Kutundan Gönderim ve Alternatif Yaklaşım',
    metaDescription: 'Instantly ve Lemlist gibi gönderim platformları ne yapar ve kimin için uygundur. Kendi gelen kutundan gönderim yaklaşımının farkı ve ne zaman daha iyidir.',
    author: 'ATAOL AI Techs',
    keyword: 'instantly alternatifi',
    excerpt: 'Gönderim platformları ile kendi gelen kutundan gönderim yaklaşımının farkı ve hangisinin kime uygun olduğu.',
    related: ['eposta-bulucu-outreach-araclari-secimi', 'b2b-eposta-bulma-rehberi'],
    body: [
      ['p', 'Instantly ve Lemlist gibi araçlar soğuk e-posta dünyasında popülerdir. Ama bu araçların ne yaptığını ve senin gerçekten ona mı yoksa daha farklı bir yaklaşıma mı ihtiyacın olduğunu netleştirmek önemli. İkisini dürüstçe karşılaştıralım.'],
      ['h2', 'Gönderim platformları ne yapar'],
      ['p', 'Instantly ve Lemlist birer gönderim platformudur. Güçlü yanları otomasyondur: yüzlerce alıcıya çok adımlı diziler gönderir, gelen kutularını ısıtır (warmup) ve tüm bunları ölçekte yönetir. Yüksek hacimli, sistematik outbound yapan satış ekipleri için tasarlanmışlardır.'],
      ['h2', 'Kimin için uygun'],
      ['p', 'Eğer işin günde yüzlerce ya da binlerce soğuk e-posta göndermeyi gerektiriyorsa ve bunu otomatik dizilerle ölçeklemek istiyorsan, bu platformlar tam bu iş için vardır. Warmup ve dizi otomasyonu bu hacimde gerçekten gerekli araçlardır.'],
      ['h2', 'Farklı bir yaklaşım: kendi gelen kutundan gönderim'],
      ['p', 'Herkesin yüksek hacimli otomasyona ihtiyacı yoktur. Satış ekibi olmayan bir kurucu ya da KOBİ için asıl değer, doğru kişiyi bulup ona gerçekten kişisel bir e-posta yazmaktır. Bu durumda mesajı kendi gelen kutundan göndermek daha basit ve daha kontrollüdür: ayrı bir gönderim altyapısı, warmup yönetimi ya da yüksek abonelik gerekmez.'],
      ['h2', 'İki yaklaşımın karşılaştırması'],
      ['table', {
        head: ['Konu', 'Gönderim platformu', 'Kendi gelen kutun'],
        rows: [
          ['Hacim', 'Yüksek (yüzler, binler)', 'Düşük ve seçili'],
          ['Otomasyon', 'Çok adımlı diziler', 'Elle ve kişisel'],
          ['Kurulum', 'Warmup ve altyapı', 'Neredeyse yok'],
          ['Kontrol', 'Platformda', 'Tamamen sende'],
        ],
      }],
      ['h2', 'AskDesk hangi yaklaşımı sunar'],
      ['p', 'AskDesk bir toplu gönderim platformu değildir. Doğru kişiyi ve doğrulanmış e-postayı bulur, o firmaya özel e-postayı yazar; sonra sen bu e-postayı kopyalar, tek tıkla Gmail de açar ya da CSV olarak dışa aktarırsın ve kendi gelen kutundan gönderirsin. Yüksek hacimli otomatik dizi istiyorsan bir gönderim platformu daha uygundur. Kişiselleştirilmiş, kontrollü ve az sürtünmeli bir ulaşım istiyorsan bu yaklaşım tam da onu verir.'],
    ],
    faq: [
      { q: 'Instantly ya da Lemlist yerine kendi gelen kutumu kullanabilir miyim?', a: 'Evet. Düşük ve seçili hacimde, doğru kişiyi bulup kişisel bir e-posta yazıp kendi kutundan göndermek daha basit ve kontrollüdür.' },
      { q: 'Gönderim platformu ne zaman gerekli?', a: 'Günde yüzlerce ya da binlerce e-postayı çok adımlı otomatik dizilerle göndermek istediğinde. Warmup ve otomasyon o hacimde gerçekten gereklidir.' },
      { q: 'AskDesk toplu gönderim yapar mı?', a: 'Hayır. AskDesk doğru kişiyi ve e-postayı bulur ve mesajı yazar; gönderimi sen kendi gelen kutundan yaparsın.' },
    ],
  },
]

export function getPost(slug) {
  return POSTS.find(p => p.slug === slug) || null
}
