// Public blog content. Pure data module (no JSX) so the prerender script can
// import slugs too. Body is a list of typed blocks rendered as React elements.
//
// Block shapes:
//   ['p', 'paragraph text']
//   ['h2', 'heading']
//   ['h3', 'subheading']
//   ['ul', ['item one', 'item two']]
//   ['table', { head: ['A', 'B'], rows: [['a1', 'b1'], ['a2', 'b2']] }]

export const POSTS = [
  {
    slug: 'b2b-eposta-bulma-rehberi',
    title: 'B2B E-posta Bulma Rehberi: Bir Firmadaki Doğru Kişiye Nasıl Ulaşılır',
    metaTitle: 'B2B E-posta Bulma Rehberi: Doğru Kişiye Nasıl Ulaşılır',
    metaDescription: 'Bir firmada karar vericinin iş e-postasını bulmanın yöntemleri: pattern mantığı, doğrulama, catch-all domainler ve KVKK. Uygulamalı, güncel rehber.',
    author: 'ATAOL AI Techs',
    keyword: 'b2b e-posta bulma',
    excerpt: 'Bir firmada karar vericinin iş e-postasını bulmanın çalışan bir sistemi: pattern mantığı, doğrulama, catch-all domainler ve KVKK.',
    related: ['karar-vericisinin-epostasini-nasil-bulursun', 'sirket-eposta-adresi-bulma-yontemleri', 'dogrulanmis-is-epostasi-bulma', 'info-yerine-dogru-kisiye-ulasmak', 'b2b-lead-listesi-olusturma'],
    body: [
      ['p', 'Bir firmayı müşteri yapmak istiyorsun. Web sitesine giriyorsun, tek gördüğün adres bir info@ kutusu. O adrese yazdığın e-postaların çoğu bir yere varmıyor, çünkü orayı kimse ciddiye almıyor. Oysa ulaşman gereken kişi belli: o firmadaki satış direktörü, kurucu ya da operasyon müdürü. Sorun onu bulmak değil, ona giden iş e-postasını bulmak.'],
      ['p', 'Bu rehber, tam olarak bunu nasıl yapacağını anlatıyor. Tahmin ve şansı bırakıp, çalışan bir sistem kuracağız.'],
      ['h2', 'Neden info@ çözüm değil'],
      ['p', 'Genel adresler (info@, iletisim@, destek@) bir havuzdur. Oraya düşen mesajlar çoğu zaman bir asistan tarafından elenir, sınıflandırılır ya da hiç açılmaz. Sana lazım olan karar verici o kutuyu genelde hiç görmez.'],
      ['p', 'İş e-postası ise kişiseldir: ad ve soyadın domaine bağlanmış halidir. Doğru kişinin kişisel iş adresine giden bir mesajın açılma ve yanıt alma olasılığı, genel bir kutuya göre kat kat yüksektir. Bu yüzden hedefimiz her zaman kişiye özel adrestir.'],
      ['h2', 'Bir iş e-postasının anatomisi'],
      ['p', 'Her iş e-postası iki parçadan oluşur: yerel kısım (@ işaretinden önce) ve domain (@ işaretinden sonra). Domaini bulmak kolaydır, firmanın web sitesidir. İş burada yerel kısmı çözmektir.'],
      ['p', 'Firmalar yerel kısmı rastgele oluşturmaz. Neredeyse tüm kurumlar tek bir kalıp kullanır ve tüm çalışanlara aynı kalıbı uygular. En yaygın kalıplar şunlardır:'],
      ['ul', ['ad.soyad@firma.com', 'adsoyad@firma.com', 'a.soyad@firma.com (ilk harf, sonra soyad)', 'asoyad@firma.com', 'ad_soyad@firma.com', 'soyad.ad@firma.com', 'ad@firma.com']],
      ['p', 'Bir firmanın hangi kalıbı kullandığını bir kez çözersen, o firmadaki herkesin adresini üretebilirsin. Bir çalışanın adresini bir yerde gördüysen (LinkedIn, web sitesi, imza), kalıbı geri çıkarıp diğerlerine uygularsın.'],
      ['h3', 'Türkçe karakter tuzağı'],
      ['p', 'Türkiye firmalarında sık atlanan bir nokta var. Şükrü Güneş adlı biri için adres neredeyse hiçbir zaman şükrü.güneş@ olmaz. Türkçe karakterler İngilizce karşılıklarına çevrilir: ş yerine s, ğ yerine g, ı yerine i, ç yerine c, ö yerine o, ü yerine u. Yani doğru tahmin sukru.gunes@firma.com olur. Bu çeviriyi yapmadan üretilen her kalıp baştan yanlıştır.'],
      ['h2', 'E-posta bulmanın dört yöntemi'],
      ['p', 'Elinde dört temel yol var. Her birinin ayrı bir gücü ve sınırı var.'],
      ['h3', '1. Web sitesi ve iletişim sayfası taraması'],
      ['p', 'Firmanın kendi sitesi çoğu zaman en dürüst kaynaktır. İletişim, hakkımızda, ekip ve kurumsal sayfalarında gerçek adresler açıkça yazabilir. Bu adresler tahmin değil, doğrulanmış gerçeklerdir. İlk adımın her zaman burası olsun.'],
      ['h3', '2. Kalıp üretme ve doğrulama'],
      ['p', 'Site adres vermiyorsa, kişinin adını ve firmanın domainini biliyorsan kalıpları üretir, sonra hangisinin gerçek olduğunu doğrularsın. Bu ikilinin birleşimi aslında bir e-posta bulucudur: üret, doğrula, gerçeği döndür. Doğrulama olmadan bu yöntem sadece tahmindir.'],
      ['h3', '3. Veritabanı tabanlı araçlar'],
      ['p', 'Hunter, Apollo gibi araçların arkasında geniş kişi veritabanları vardır. Bir domain verirsin, sana o firmadaki kişileri ve adreslerini döndürür. Kapsamları geniştir ama maliyetlidir ve her firmayı, özellikle küçük yerel firmaları bilmezler.'],
      ['h3', '4. LinkedIn üzerinden çapraz doğrulama'],
      ['p', 'LinkedIn, doğru kişiyi ve unvanını bulmak için en iyi yerdir. Adresi doğrudan vermez ama adı ve firmayı verir. Adı alıp kalıba çevirir, doğrularsın. Ayrıca bir kişinin gerçek adresini bir yerde görürsen, firmanın kalıbını çözmek için çapraz kontrol sağlar.'],
      ['h2', 'Doğrulama olmadan tahmin işe yaramaz'],
      ['p', 'Burası çoğu rehberin atladığı yer. Bir kalıp ürettin diyelim: ad.soyad@firma.com. Bu adres gerçekten var mı, yoksa boşa mı yazıyorsun? Doğrulama bunu söyler.'],
      ['p', 'Doğrulama üç katmanda çalışır:'],
      ['ul', ['MX kaydı: Domainin e-posta alabilen bir sunucusu var mı. Yoksa hiçbir adres çalışmaz.', 'Kutu kontrolü: Sunucuya bağlanıp o yerel kısmın gerçekten var olup olmadığı sorulur.', 'Catch-all durumu: Bazı firmalar her adrese evet der ayarındadır. Bu durumda hangi kalıbın gerçek olduğunu ayırt edemezsin.']],
      ['p', 'Doğrulamayı atlamanın bedeli bounce tur. Var olmayan adreslere gönderim yaptıkça gönderen itibarın düşer ve zamanla gerçek adreslere bile ulaşamamaya başlarsın.'],
      ['h2', 'KVKK ve soğuk iletişimde e-posta'],
      ['p', 'Türkiye de e-posta ile soğuk iletişim yaparken iki çerçeveyi bilmek gerekir. Kişisel verilerin işlenmesi KVKK kapsamındadır. Ticari elektronik ileti gönderimi ise 6563 sayılı kanun ve İleti Yönetim Sistemi (İYS) ile düzenlenir. Bu bir hukuki tavsiye değildir; ölçeklenmeden önce bir hukukçuya danışmanı öneririz. Doğru yaklaşım, az sayıda ve gerçekten ilgili firmaya kişiselleştirilmiş ulaşmaktır.'],
      ['h2', 'Hangi yöntem sana uygun'],
      ['p', 'Solo kurucuysan ve az sayıda ama doğru firmayı hedefliyorsan, site taraması ve kalıp artı doğrulama kombinasyonu genelde yeter. Hacmin arttıkça veritabanı tabanlı bir aracı doğrulamayla birlikte kullanmak işini hızlandırır. Değişmeyen sıralama şudur: önce doğru kişiyi belirle, sonra adresi üret, sonra mutlaka doğrula, en son gönder.'],
    ],
    faq: [
      { q: 'Bir firmanın kullandığı e-posta kalıbını nasıl anlarım?', a: 'O firmadan bir kişinin gerçek adresini bir yerde bulup adını kalıba geri çevirirsin. Örneğin a.gunes@firma.com adresi, firmanın ilk harf nokta soyad kalıbını kullandığını gösterir.' },
      { q: 'Tahmin ettiğim adresin gerçek olduğunu nasıl bilirim?', a: 'Doğrulama ile. MX kaydı, kutu kontrolü ve catch-all durumu bakılır. Catch-all olmayan bir domainde doğrulama kesin sonuç verir.' },
      { q: 'Sadece info@ adresi bulabiliyorum, ne yapmalıyım?', a: 'Önce LinkedIn den doğru kişiyi bul, adını firma domainiyle birleştirip kalıp üret ve doğrula. Başka yol yoksa info@ üzerinden yazarken konuya doğru kişinin adını ekle.' },
    ],
  },

  {
    slug: 'karar-vericisinin-epostasini-nasil-bulursun',
    title: 'Bir Firmanın Karar Vericisinin E-postasını Nasıl Bulursun',
    metaTitle: 'Karar Vericinin E-postasını Bulma: Adım Adım',
    metaDescription: 'Bir firmada doğru karar vericiyi belirleyip iş e-postasına ulaşmanın adım adım yolu: unvan haritası, kalıp üretme, doğrulama ve alternatif kişi.',
    author: 'ATAOL AI Techs',
    keyword: 'karar verici e-postası bulma',
    excerpt: 'Doğru karar vericiyi belirleyip e-postasına ulaşmanın tek firma üzerinden adım adım anlatımı.',
    related: ['b2b-eposta-bulma-rehberi', 'info-yerine-dogru-kisiye-ulasmak', 'dogrulanmis-is-epostasi-bulma'],
    body: [
      ['p', 'Karar vericinin e-postasını bulmak iki işi karıştırmamakla başlar: önce doğru kişiyi belirlemek, sonra o kişinin adresini bulmak. Çoğu kişi ikinciyle uğraşıp birinciyi atlar ve yanlış insana yazar. Bu yazıda tek bir firma üzerinden, sırayla ilerleyeceğiz.'],
      ['h2', 'Adım 1: Doğru unvanı belirle'],
      ['p', 'Sunduğun şeye göre kararı verecek kişi değişir. Yazacağın kişi, teklifinden en çok etkilenen ve bütçesine hükmeden kişidir. Kaba bir harita:'],
      ['ul', ['Satış veya pazarlama çözümü satıyorsan: Satış Direktörü, Pazarlama Müdürü, CMO', 'Operasyon veya verimlilik çözümü: Operasyon Müdürü, COO', 'Yazılım veya teknik ürün: CTO, Teknoloji Müdürü, Ürün Müdürü', 'İnsan kaynakları çözümü: İK Müdürü, People Lead', 'Küçük firma veya erken startup: doğrudan kurucu ya da genel müdür']],
      ['p', 'Kural şudur: 10 kişilik bir firmada kurucuya yaz, 500 kişilik bir firmada ilgili departman müdürüne. Büyük firmada kurucuya yazmak neredeyse hiç yanıt getirmez.'],
      ['h2', 'Adım 2: O kişinin adını bul'],
      ['p', 'Unvanı belirledin, şimdi o unvandaki gerçek kişiyi bulacaksın. En hızlı kaynak LinkedIn: firma sayfasına gir, çalışanlar sekmesinden unvana göre filtrele. İkinci kaynak firmanın ekip veya yönetim sayfasıdır. Üçüncüsü basın haberleri ve etkinlik konuşmacı listeleridir; yöneticiler oralarda adıyla geçer.'],
      ['h2', 'Adım 3: Adı firma kalıbına çevir'],
      ['p', 'Adı ve firmanın domainini biliyorsun. Şimdi olası adresleri üret. Firmalar tek bir kalıp kullanır, o yüzden en yaygın kalıpları sırayla dener, doğrularsın. Kalıpların tam listesi ve Türkçe karakter çevirisi için B2B e-posta bulma rehberimize bakabilirsin. Kısaca: en olası aday ad.soyad@domain ve a.soyad@domain kalıplarıdır.'],
      ['h2', 'Adım 4: Adayları doğrula'],
      ['p', 'Ürettiğin adayların hangisi gerçek? Doğrulama söyler. Adayları en olasıdan başlayarak doğrula, ilk geçerli olanda dur. Domain catch-all ise doğrulama karar veremez; o zaman en olası kalıbı tahmin olarak alırsın. Doğrulamanın nasıl çalıştığını doğrulanmış e-posta yazımızda ayrıntılı anlattık.'],
      ['h2', 'Adım 5: Bulamazsan kademeli in'],
      ['p', 'Karar vericinin adresini bir türlü doğrulayamıyorsan boşuna ısrar etme. Bir kademe alta in: o kişinin ekibinden birine ulaş, seni doğru kişiye yönlendirsin. Ya da bulduğun geçerli bir adres varsa, mesajında asıl konuşmak istediğin kişinin adını ve unvanını belirt; iç yönlendirme çoğu zaman işe yarar.'],
      ['h2', 'Örnek: tek firma üzerinden'],
      ['p', 'Diyelim ki bir e-ticaret KOBİ sine lojistik yazılımı satıyorsun. Karar verici muhtemelen Operasyon Müdürü. LinkedIn de firmanın operasyon müdürünün Deniz Yılmaz olduğunu buldun. Firmanın sitesinde bir çalışanın imzasında a.kaya@firma.com gördün, demek ki kalıp ilk harf nokta soyad. O halde en güçlü aday d.yilmaz@firma.com. Doğruladın, geçerli çıktı. Artık doğru kişiye, doğru adrese yazabilirsin.'],
    ],
    faq: [
      { q: 'Büyük bir firmada kime yazmalıyım?', a: 'Kurucuya değil, teklifinle ilgili departmanın müdürüne. Büyük firmada kurucuya yazılan soğuk e-postalar neredeyse hiç yanıt almaz.' },
      { q: 'Doğru kişiyi buldum ama e-postasını doğrulayamıyorum, ne yaparım?', a: 'Bir kademe alta inip ekibinden birine ulaş ya da geçerli başka bir adrese yazıp mesajında asıl kişinin adını ve unvanını belirterek iç yönlendirme iste.' },
      { q: 'LinkedIn dışında doğru kişiyi nereden bulabilirim?', a: 'Firmanın ekip ve yönetim sayfaları, basın haberleri ve sektör etkinliklerinin konuşmacı listeleri iyi kaynaklardır.' },
    ],
  },

  {
    slug: 'sirket-eposta-adresi-bulma-yontemleri',
    title: 'Şirket E-posta Adresi Bulma Yöntemleri',
    metaTitle: 'Şirket E-posta Adresi Bulma Yöntemleri',
    metaDescription: 'Bir şirketin e-posta adresini bulmanın ücretsiz ve ücretli yöntemleri, doğruluk ve maliyet karşılaştırması, Google arama operatörleri ve catch-all gerçeği.',
    author: 'ATAOL AI Techs',
    keyword: 'şirket e-posta adresi bulma',
    excerpt: 'Ücretsiz ve ücretli yöntemleri doğruluk, hız ve maliyet açısından dürüstçe karşılaştıran uygulamalı bir rehber.',
    related: ['b2b-eposta-bulma-rehberi', 'dogrulanmis-is-epostasi-bulma', 'karar-vericisinin-epostasini-nasil-bulursun'],
    body: [
      ['p', 'Bir şirketin e-posta adresini bulmanın birden çok yolu var ve hepsi aynı sonucu vermez. Bazıları bedava ama yavaş, bazıları hızlı ama maliyetli. Bu yazıda yöntemleri açıkça karşılaştırıp hangi durumda hangisini seçeceğini netleştiriyoruz.'],
      ['h2', 'Ücretsiz yöntemler'],
      ['p', 'Para harcamadan gidebileceğin üç yol var. İlki, firmanın web sitesini taramak: iletişim, hakkımızda ve ekip sayfalarında gerçek adresler açıkça yazabilir. İkincisi, Google arama operatörleriyle adresleri açığa çıkarmak. Üçüncüsü, kişinin adını firmanın kalıbına çevirip aday adresler üretmek.'],
      ['h3', 'Google arama operatörü örnekleri'],
      ['p', 'Arama motoru, sitenin gömdüğü adresleri bulmak için güçlü bir araçtır. Şu kalıpları dene:'],
      ['ul', ['site:firma.com e-posta ya da site:firma.com iletisim', '"@firma.com" ile firma adı birlikte aratmak', 'Kişinin adı ile "@firma.com" birlikte aratmak', 'intext operatörüyle belirli bir unvanı ve firmayı aramak']],
      ['h2', 'Ücretli araçlar ne katar'],
      ['p', 'Hunter, Apollo gibi araçların arkasında geniş veritabanları vardır. Domaini verirsin, firmadaki kişileri ve adresleri döndürür. Sana kazandırdığı şey hız ve kapsamdır. Sınırı ise şudur: küçük ve yerel firmaları çoğu zaman bilmezler, ve maliyet kullanımla birlikte artar.'],
      ['h2', 'Yöntem karşılaştırması'],
      ['table', {
        head: ['Yöntem', 'Doğruluk', 'Hız', 'Maliyet'],
        rows: [
          ['Site tarama', 'Yüksek (gerçek adres)', 'Yavaş', 'Bedava'],
          ['Google operatörleri', 'Orta', 'Orta', 'Bedava'],
          ['Kalıp + doğrulama', 'Yüksek (doğrulanırsa)', 'Hızlı', 'Düşük'],
          ['Veritabanı aracı', 'Değişken', 'Çok hızlı', 'Yüksek'],
        ],
      }],
      ['h2', 'Catch-all gerçeği'],
      ['p', 'Hangi yöntemi seçersen seç, bir adresin gerçekten çalıştığından emin olmak için doğrulama gerekir. Ama bazı domainler catch-all ayarındadır: var olmayan adreslere bile kabul derler. Böyle bir domainde doğrulama hangi kalıbın gerçek olduğunu söyleyemez, en olası kalıbı tahmin olarak alırsın. Bu, ücretli aracın bile kesin sonuç veremeyeceği bir durumdur.'],
      ['h2', 'Yasal sınır'],
      ['p', 'Herkese açık kaynaklardan iş iletişim bilgisi bulmak yaygın bir pratiktir. Kritik olan bu veriyi nasıl kullandığındır. KVKK ve ticari elektronik ileti kurallarına uygun, kişiselleştirilmiş ve alakalı iletişim kur; toplu ve izinsiz gönderimden kaçın.'],
    ],
    faq: [
      { q: 'Bir şirketin e-postasını tamamen ücretsiz bulabilir miyim?', a: 'Çoğu zaman evet. Site tarama, Google operatörleri ve kalıp üretme bedavadır. Eksik olan tek şey doğrulamadır; onun için genelde ucuz bir araç gerekir.' },
      { q: 'Google ile adres bulmak için hangi operatörü kullanmalıyım?', a: 'site:firma.com iletisim ve firma adıyla birlikte "@firma.com" aramaları en çok işe yarayanlardır.' },
      { q: 'Ücretli araç her firmayı bulur mu?', a: 'Hayır. Veritabanları büyük ve bilinen firmalarda güçlüdür; küçük ve yerel firmalarda çoğu zaman eksik kalır.' },
    ],
  },

  {
    slug: 'info-yerine-dogru-kisiye-ulasmak',
    title: 'info@ Yerine Doğru Kişiye Ulaşmak: Genel Adreslerin Tuzağı',
    metaTitle: 'info@ Yerine Doğru Kişiye Ulaşmak',
    metaDescription: 'Genel e-posta adresleri neden yanıt getirmez ve karar vericiye nasıl ulaşırsın. info@ elindeyse ne yapman gerektiği ve örnek ilk temas mesajı.',
    author: 'ATAOL AI Techs',
    keyword: 'info e-posta yerine doğru kişi',
    excerpt: 'Genel adreslerin neden çalışmadığı ve karar vericiye ulaşmanın pratik yolları, örnek ilk temas mesajıyla.',
    related: ['b2b-eposta-bulma-rehberi', 'karar-vericisinin-epostasini-nasil-bulursun'],
    body: [
      ['p', 'Bir firmaya ulaşmak istiyorsun ama elindeki tek adres info@ ya da iletisim@. O adrese yazdığın mesajların çoğunun neden yanıtsız kaldığını ve gerçekten doğru kişiye nasıl ulaşacağını anlatalım.'],
      ['h2', 'Genel adresler neden yanıtlanmaz'],
      ['p', 'Genel kutular bir ortak havuzdur. Genelde bir asistan, resepsiyon ya da otomatik bir sistem tarafından karşılanır. Gelen mesajlar müşteri talebi, fatura, başvuru gibi kategorilere ayrılır. Senin soğuk teklifin bu akışta en düşük önceliklidir ve karar vericiye çoğu zaman hiç ulaşmaz. Yani sorun mesajının değil, kutunun kendisidir.'],
      ['h2', 'Karar vericiye ulaşmanın üç yolu'],
      ['p', 'info@ ile uğraşmak yerine doğru kişinin kişisel iş adresini hedefle. Üç yol var. Birincisi, LinkedIn den doğru unvandaki kişiyi bul, adını firma kalıbına çevir ve doğrula. İkincisi, firmanın ekip sayfasından adları topla. Üçüncüsü, elindeki geçerli bir adres varsa oradan iç yönlendirme iste. Bu yolların ayrıntısı için karar vericinin e-postasını bulma yazımıza bakabilirsin.'],
      ['h2', 'info@ elindeyse ne yapmalı'],
      ['p', 'Bazen küçük bir firmada gerçekten tek kutu info@ dır ve karar verici de onu okur. Bu durumda info@ kötü bir seçenek değildir, yeter ki mesajını doğru kurgula. İki şeye dikkat et: konuya ulaşmak istediğin kişinin adını ve unvanını ekle ki mesaj doğru kişiye yönlendirilsin, ve ilk cümlede neden yazdığını net söyle ki eleyen kişi değerini anlasın.'],
      ['h2', 'Örnek ilk temas'],
      ['p', 'Konu: Deniz Yılmaz için, operasyon verimliliği. Merhaba, mesajımı operasyondan sorumlu Deniz Yılmaz a iletebilir misiniz. Firmanızın sipariş yoğunluğu arttıkça hazırlık sürelerini kısaltan bir çözüm üzerinde çalışıyoruz. Kısa bir örnek gönderebilirim, ilgilenirse birkaç dakikalık bir görüşme ayarlayabiliriz. Teşekkürler.'],
      ['p', 'Bu mesaj kısa, doğru kişiyi adıyla işaret ediyor ve eleyen kişiye ne yapması gerektiğini söylüyor. info@ üzerinden bile yanıt alma şansın böyle artar.'],
    ],
    faq: [
      { q: 'info@ adresine yazmak tamamen zaman kaybı mı?', a: 'Hayır. Küçük firmalarda karar verici o kutuyu okuyabilir. Mesajında doğru kişinin adını belirtir ve değeri net anlatırsan yanıt şansın artar.' },
      { q: 'Karar vericinin kişisel adresini bulamıyorum, ne yaparım?', a: 'LinkedIn den adını bulup firma kalıbına çevir ve doğrula. Olmazsa geçerli başka bir adrese yazıp iç yönlendirme iste.' },
    ],
  },

  {
    slug: 'dogrulanmis-is-epostasi-bulma',
    title: 'Doğrulanmış İş E-postası Bulma: Ücretsiz ve Ücretli Yöntemler',
    metaTitle: 'Doğrulanmış İş E-postası Bulma',
    metaDescription: 'E-posta doğrulama neden şart, nasıl çalışır ve bounce oranını nasıl düşürürsün. Ücretsiz sınırlar, kullanım başına doğrulama ve Türkiye den gönderimde dikkat.',
    author: 'ATAOL AI Techs',
    keyword: 'e-posta doğrulama',
    excerpt: 'Doğrulamanın teknik gerçeği, ücretsiz ve ücretli seçenekler ve bounce oranını düşürmenin somut yolları.',
    related: ['b2b-eposta-bulma-rehberi', 'sirket-eposta-adresi-bulma-yontemleri'],
    body: [
      ['p', 'Bir e-posta adresi bulmak yarısıdır. Diğer yarısı o adresin gerçekten çalıştığından emin olmaktır. Doğrulama bunu yapar ve atlanırsa hem isabetin hem de gönderme yeteneğin zarar görür.'],
      ['h2', 'Doğrulama neden şart'],
      ['p', 'Var olmayan bir adrese gönderim yaptığında mesaj geri döner, buna bounce denir. Bounce oranın yükseldikçe e-posta sağlayıcıları seni şüpheli görür ve gönderen itibarın düşer. Sonuçta gerçek ve geçerli adreslere gönderdiğin mesajlar bile spam klasörüne düşmeye başlar. Yani doğrulama sadece bu adres doğru mu sorusu değil, uzun vadede gönderebiliyor muyum sorusudur.'],
      ['h2', 'Doğrulama nasıl çalışır'],
      ['p', 'Doğrulama katmanlı bir kontroldür. Önce MX kaydına bakılır: domainin e-posta alabilen bir sunucusu var mı. Yoksa hiçbir adres çalışmaz. Sonra sunucuya bağlanılıp o yerel kısmın var olup olmadığı sorulur. Cevaba göre adres geçerli, geçersiz ya da belirsiz olarak işaretlenir.'],
      ['h3', 'Catch-all neden belirsizlik yaratır'],
      ['p', 'Bazı domainler catch-all ayarındadır: var olmayan adreslere bile kabul derler. Böyle bir sunucu her adaya evet dediği için hangi kalıbın gerçek olduğunu ayırt edemezsin. Bu domainlerde doğrulama sana kesin bir evet veremez; en olası kalıbı tahmin olarak, düşük güvenle alırsın. Bunu bilmek, sonuçları yanlış yorumlamanı engeller.'],
      ['h2', 'Ücretsiz sınırlar ve kullanım başına doğrulama'],
      ['p', 'Kendi altyapında SMTP seviyesinde doğrulama yapmak çoğu ortamda mümkün değildir, çünkü giden bağlantılar engellidir. Bu yüzden pratikte bir doğrulama servisi kullanılır. Bu servislerin çoğu az sayıda ücretsiz deneme kredisi verir, sonrası kullanım başınadır. Kullanım başına model startuplar için sağlıklıdır: maliyet ancak gerçekten doğrulama yaptığında oluşur, sabit bir abonelik yükü olmaz.'],
      ['h2', 'Bounce oranını düşürme taktikleri'],
      ['ul', ['Göndermeden önce her adresi doğrula, tahminle gönderme.', 'Catch-all domainlerdeki tahmin adreslere toplu gönderim yapma, tek tek ve dikkatli git.', 'Listeyi temiz tut; eski ve tepki almayan adresleri ayıkla.', 'Yeni bir gönderen alan adında hacmi yavaş yavaş artır.']],
      ['h2', 'Türkiye den gönderimde dikkat'],
      ['p', 'Gönderdiğin domainin kimlik kayıtları (SPF ve DKIM) düzgün ayarlı olmalı ki mesajların spam e düşmesin. Ayrıca ticari elektronik ileti kurallarına uy: gerçekten ilgili ve az sayıda alıcıya kişiselleştirilmiş yaz. Doğrulama isabeti artırır ama kuralları o değil, senin yaklaşımın belirler.'],
    ],
    faq: [
      { q: 'Doğrulama olmadan gönderirsem ne olur?', a: 'Var olmayan adreslere gönderim bounce üretir, gönderen itibarın düşer ve zamanla geçerli adreslere bile ulaşamamaya başlarsın.' },
      { q: 'Catch-all domainde adresi kesin doğrulayabilir miyim?', a: 'Hayır. Catch-all sunucu her adrese kabul dediği için doğrulama karar veremez; en olası kalıbı tahmin olarak, düşük güvenle alırsın.' },
      { q: 'Kendi başıma doğrulama yapabilir miyim?', a: 'Çoğu ortamda giden SMTP bağlantıları engelli olduğu için pratikte bir doğrulama servisi kullanılır. Kullanım başına ödeme modeli startuplar için en uygunudur.' },
    ],
  },

  {
    slug: 'b2b-lead-listesi-olusturma',
    title: 'B2B Lead Listesi Sıfırdan Nasıl Oluşturulur',
    metaTitle: 'B2B Lead Listesi Nasıl Oluşturulur',
    metaDescription: 'İdeal müşteri profilinden CSV çıktısına kadar B2B lead listesi oluşturmanın uçtan uca sistemi: kaynaklar, doğru kişi ve e-posta, kolon şablonu ve outreach.',
    author: 'ATAOL AI Techs',
    keyword: 'b2b lead listesi oluşturma',
    excerpt: 'İdeal müşteri profilinden outreach a hazır CSV ye kadar uçtan uca, uygulanabilir bir lead listesi sistemi.',
    related: ['b2b-eposta-bulma-rehberi', 'karar-vericisinin-epostasini-nasil-bulursun', 'dogrulanmis-is-epostasi-bulma'],
    body: [
      ['p', 'İyi bir lead listesi rastgele toplanmış isimler değildir. Doğru firmalar, doğru kişiler ve doğrulanmış adreslerden oluşan, kullanıma hazır bir yapıdır. Bu yazıda ideal müşteri profilinden outreach a hazır bir CSV ye kadar sistemi kuruyoruz.'],
      ['h2', 'Adım 1: İdeal müşteri profilini tanımla'],
      ['p', 'Herkesi hedeflemek hiç kimseyi hedeflememektir. Önce ideal müşterini birkaç somut ölçütle tanımla: sektör, firma büyüklüğü (çalışan sayısı), lokasyon ve seni gerçekten ihtiyaç duyar hale getiren tetikleyici durum. Örneğin sipariş hacmi büyüyen 20 ila 100 çalışanlı e-ticaret firmaları. Bu netlik, listenin geri kalanını kolaylaştırır.'],
      ['h2', 'Adım 2: Hedef firma listesi çıkar'],
      ['p', 'Profiline uyan firmaları toplamak için birden çok kaynağı birleştir. Sektör dizinleri ve ticaret odası listeleri, Google Haritalar aramaları, LinkedIn firma aramaları ve sektörel etkinlik katılımcı listeleri iyi başlangıçlardır. Amaç 20 ila 50 gerçekten uygun firmadır, binlerce alakasız isim değil.'],
      ['h2', 'Adım 3: Her firmada doğru kişi ve e-posta'],
      ['p', 'Firma listesi tek başına yetmez, her firmada karar vericiyi ve adresini bulman gerekir. Unvanı belirle, kişiyi LinkedIn den bul, adını firma kalıbına çevir ve doğrula. Bu sürecin ayrıntısı için karar vericinin e-postasını bulma yazımıza bakabilirsin.'],
      ['h2', 'Adım 4: Listeyi doğru kolonlarla yapılandır'],
      ['p', 'Listeyi bir araca aktaracaksan kolonların standart olması gerekir. Çoğu outreach aracının beklediği asgari yapı şudur:'],
      ['table', {
        head: ['Kolon', 'Açıklama'],
        rows: [
          ['email', 'Doğrulanmış iş e-postası'],
          ['first_name', 'Kişinin adı (kişiselleştirme için)'],
          ['company', 'Firma adı'],
          ['title', 'Unvan'],
          ['website', 'Firma domaini'],
        ],
      }],
      ['p', 'Bu kolonları CSV olarak dışa aktardığında, liste Instantly ya da Lemlist gibi araçlara doğrudan yüklenebilir hale gelir.'],
      ['h2', 'Adım 5: Listeyi outreach a dönüştür'],
      ['p', 'Liste hazır olduğunda son adım kişiselleştirilmiş ulaşımdır. Her satır için firmaya özel, kısa ve tek çağrılı bir mesaj yaz. Toplu ve aynı metni gönderme; first_name ve company kolonlarını kullanarak her mesajı ilgili kişiye özel hale getir. Az sayıda ama isabetli gönderim, çok sayıda alakasız gönderimden her zaman daha iyidir.'],
      ['h2', 'Türkiye ve ihracat için kaynak farkı'],
      ['p', 'Yurt içi listelerde ticaret odası kayıtları, sektör dernekleri ve Google Haritalar güçlü kaynaklardır. İhracat hedefliyorsan hedef ülkenin sektör dizinleri, fuar katılımcı listeleri ve LinkedIn ülke filtreleri devreye girer. Her iki durumda da mantık aynıdır: profil, firma, kişi, adres, doğrulama.'],
    ],
    faq: [
      { q: 'Lead listesi ne kadar büyük olmalı?', a: 'Büyüklük değil isabet önemlidir. 20 ila 50 gerçekten uygun firma, binlerce alakasız isimden çok daha iyi sonuç verir.' },
      { q: 'CSV de hangi kolonlar olmalı?', a: 'Asgari olarak email, first_name, company, title ve website. Bu yapı çoğu outreach aracına doğrudan yüklenir.' },
      { q: 'İhracat için lead listesini nereden çıkarırım?', a: 'Hedef ülkenin sektör dizinleri, fuar katılımcı listeleri ve LinkedIn ülke filtreleri en verimli kaynaklardır.' },
    ],
  },
]

export function getPost(slug) {
  return POSTS.find(p => p.slug === slug) || null
}
